// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: nodevault/v1/nodevault.proto

package nodevaultv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_GetPolicyBundle_FullMethodName = "/nodevault.v1.PolicyService/GetPolicyBundle"
	PolicyService_ListPolicies_FullMethodName    = "/nodevault.v1.PolicyService/ListPolicies"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	GetPolicyBundle(ctx context.Context, in *GetPolicyBundleRequest, opts ...grpc.CallOption) (*PolicyBundle, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) GetPolicyBundle(ctx context.Context, in *GetPolicyBundleRequest, opts ...grpc.CallOption) (*PolicyBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyBundle)
	err := c.cc.Invoke(ctx, PolicyService_GetPolicyBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, PolicyService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
type PolicyServiceServer interface {
	GetPolicyBundle(context.Context, *GetPolicyBundleRequest) (*PolicyBundle, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) GetPolicyBundle(context.Context, *GetPolicyBundleRequest) (*PolicyBundle, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicyBundle not implemented")
}
func (UnimplementedPolicyServiceServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_GetPolicyBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).GetPolicyBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_GetPolicyBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).GetPolicyBundle(ctx, req.(*GetPolicyBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicyBundle",
			Handler:    _PolicyService_GetPolicyBundle_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _PolicyService_ListPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	BuildService_BuildAndRegister_FullMethodName = "/nodevault.v1.BuildService/BuildAndRegister"
	BuildService_ResolveToolSpec_FullMethodName  = "/nodevault.v1.BuildService/ResolveToolSpec"
)

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildServiceClient interface {
	BuildAndRegister(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildEvent], error)
	ResolveToolSpec(ctx context.Context, in *ToolSpecRequest, opts ...grpc.CallOption) (*ResolvedToolSpecResponse, error)
}

type buildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildServiceClient(cc grpc.ClientConnInterface) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) BuildAndRegister(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BuildEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BuildService_ServiceDesc.Streams[0], BuildService_BuildAndRegister_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildRequest, BuildEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildService_BuildAndRegisterClient = grpc.ServerStreamingClient[BuildEvent]

func (c *buildServiceClient) ResolveToolSpec(ctx context.Context, in *ToolSpecRequest, opts ...grpc.CallOption) (*ResolvedToolSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvedToolSpecResponse)
	err := c.cc.Invoke(ctx, BuildService_ResolveToolSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
// All implementations must embed UnimplementedBuildServiceServer
// for forward compatibility.
type BuildServiceServer interface {
	BuildAndRegister(*BuildRequest, grpc.ServerStreamingServer[BuildEvent]) error
	ResolveToolSpec(context.Context, *ToolSpecRequest) (*ResolvedToolSpecResponse, error)
	mustEmbedUnimplementedBuildServiceServer()
}

// UnimplementedBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildServiceServer struct{}

func (UnimplementedBuildServiceServer) BuildAndRegister(*BuildRequest, grpc.ServerStreamingServer[BuildEvent]) error {
	return status.Error(codes.Unimplemented, "method BuildAndRegister not implemented")
}
func (UnimplementedBuildServiceServer) ResolveToolSpec(context.Context, *ToolSpecRequest) (*ResolvedToolSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveToolSpec not implemented")
}
func (UnimplementedBuildServiceServer) mustEmbedUnimplementedBuildServiceServer() {}
func (UnimplementedBuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildServiceServer will
// result in compilation errors.
type UnsafeBuildServiceServer interface {
	mustEmbedUnimplementedBuildServiceServer()
}

func RegisterBuildServiceServer(s grpc.ServiceRegistrar, srv BuildServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildService_ServiceDesc, srv)
}

func _BuildService_BuildAndRegister_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuildServiceServer).BuildAndRegister(m, &grpc.GenericServerStream[BuildRequest, BuildEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildService_BuildAndRegisterServer = grpc.ServerStreamingServer[BuildEvent]

func _BuildService_ResolveToolSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).ResolveToolSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_ResolveToolSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).ResolveToolSpec(ctx, req.(*ToolSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildService_ServiceDesc is the grpc.ServiceDesc for BuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveToolSpec",
			Handler:    _BuildService_ResolveToolSpec_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildAndRegister",
			Handler:       _BuildService_BuildAndRegister_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	ValidateService_DryRun_FullMethodName   = "/nodevault.v1.ValidateService/DryRun"
	ValidateService_SmokeRun_FullMethodName = "/nodevault.v1.ValidateService/SmokeRun"
)

// ValidateServiceClient is the client API for ValidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateServiceClient interface {
	DryRun(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*DryRunResult, error)
	SmokeRun(ctx context.Context, in *SmokeRunRequest, opts ...grpc.CallOption) (*SmokeRunResult, error)
}

type validateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateServiceClient(cc grpc.ClientConnInterface) ValidateServiceClient {
	return &validateServiceClient{cc}
}

func (c *validateServiceClient) DryRun(ctx context.Context, in *DryRunRequest, opts ...grpc.CallOption) (*DryRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunResult)
	err := c.cc.Invoke(ctx, ValidateService_DryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validateServiceClient) SmokeRun(ctx context.Context, in *SmokeRunRequest, opts ...grpc.CallOption) (*SmokeRunResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SmokeRunResult)
	err := c.cc.Invoke(ctx, ValidateService_SmokeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateServiceServer is the server API for ValidateService service.
// All implementations must embed UnimplementedValidateServiceServer
// for forward compatibility.
type ValidateServiceServer interface {
	DryRun(context.Context, *DryRunRequest) (*DryRunResult, error)
	SmokeRun(context.Context, *SmokeRunRequest) (*SmokeRunResult, error)
	mustEmbedUnimplementedValidateServiceServer()
}

// UnimplementedValidateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidateServiceServer struct{}

func (UnimplementedValidateServiceServer) DryRun(context.Context, *DryRunRequest) (*DryRunResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRun not implemented")
}
func (UnimplementedValidateServiceServer) SmokeRun(context.Context, *SmokeRunRequest) (*SmokeRunResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SmokeRun not implemented")
}
func (UnimplementedValidateServiceServer) mustEmbedUnimplementedValidateServiceServer() {}
func (UnimplementedValidateServiceServer) testEmbeddedByValue()                         {}

// UnsafeValidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateServiceServer will
// result in compilation errors.
type UnsafeValidateServiceServer interface {
	mustEmbedUnimplementedValidateServiceServer()
}

func RegisterValidateServiceServer(s grpc.ServiceRegistrar, srv ValidateServiceServer) {
	// If the following call panics, it indicates UnimplementedValidateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidateService_ServiceDesc, srv)
}

func _ValidateService_DryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServiceServer).DryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidateService_DryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServiceServer).DryRun(ctx, req.(*DryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidateService_SmokeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmokeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServiceServer).SmokeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidateService_SmokeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServiceServer).SmokeRun(ctx, req.(*SmokeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidateService_ServiceDesc is the grpc.ServiceDesc for ValidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.ValidateService",
	HandlerType: (*ValidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DryRun",
			Handler:    _ValidateService_DryRun_Handler,
		},
		{
			MethodName: "SmokeRun",
			Handler:    _ValidateService_SmokeRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	ToolRegistryService_RegisterTool_FullMethodName = "/nodevault.v1.ToolRegistryService/RegisterTool"
	ToolRegistryService_GetTool_FullMethodName      = "/nodevault.v1.ToolRegistryService/GetTool"
	ToolRegistryService_ListTools_FullMethodName    = "/nodevault.v1.ToolRegistryService/ListTools"
	ToolRegistryService_RetractTool_FullMethodName  = "/nodevault.v1.ToolRegistryService/RetractTool"
	ToolRegistryService_DeleteTool_FullMethodName   = "/nodevault.v1.ToolRegistryService/DeleteTool"
)

// ToolRegistryServiceClient is the client API for ToolRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolRegistryServiceClient interface {
	RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error)
	GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*RegisteredToolDefinition, error)
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	RetractTool(ctx context.Context, in *RetractToolRequest, opts ...grpc.CallOption) (*RetractToolResponse, error)
	DeleteTool(ctx context.Context, in *DeleteToolRequest, opts ...grpc.CallOption) (*DeleteToolResponse, error)
}

type toolRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolRegistryServiceClient(cc grpc.ClientConnInterface) ToolRegistryServiceClient {
	return &toolRegistryServiceClient{cc}
}

func (c *toolRegistryServiceClient) RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToolResponse)
	err := c.cc.Invoke(ctx, ToolRegistryService_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolRegistryServiceClient) GetTool(ctx context.Context, in *GetToolRequest, opts ...grpc.CallOption) (*RegisteredToolDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisteredToolDefinition)
	err := c.cc.Invoke(ctx, ToolRegistryService_GetTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolRegistryServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, ToolRegistryService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolRegistryServiceClient) RetractTool(ctx context.Context, in *RetractToolRequest, opts ...grpc.CallOption) (*RetractToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractToolResponse)
	err := c.cc.Invoke(ctx, ToolRegistryService_RetractTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolRegistryServiceClient) DeleteTool(ctx context.Context, in *DeleteToolRequest, opts ...grpc.CallOption) (*DeleteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteToolResponse)
	err := c.cc.Invoke(ctx, ToolRegistryService_DeleteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolRegistryServiceServer is the server API for ToolRegistryService service.
// All implementations must embed UnimplementedToolRegistryServiceServer
// for forward compatibility.
type ToolRegistryServiceServer interface {
	RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error)
	GetTool(context.Context, *GetToolRequest) (*RegisteredToolDefinition, error)
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	RetractTool(context.Context, *RetractToolRequest) (*RetractToolResponse, error)
	DeleteTool(context.Context, *DeleteToolRequest) (*DeleteToolResponse, error)
	mustEmbedUnimplementedToolRegistryServiceServer()
}

// UnimplementedToolRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolRegistryServiceServer struct{}

func (UnimplementedToolRegistryServiceServer) RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedToolRegistryServiceServer) GetTool(context.Context, *GetToolRequest) (*RegisteredToolDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTool not implemented")
}
func (UnimplementedToolRegistryServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedToolRegistryServiceServer) RetractTool(context.Context, *RetractToolRequest) (*RetractToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetractTool not implemented")
}
func (UnimplementedToolRegistryServiceServer) DeleteTool(context.Context, *DeleteToolRequest) (*DeleteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTool not implemented")
}
func (UnimplementedToolRegistryServiceServer) mustEmbedUnimplementedToolRegistryServiceServer() {}
func (UnimplementedToolRegistryServiceServer) testEmbeddedByValue()                             {}

// UnsafeToolRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolRegistryServiceServer will
// result in compilation errors.
type UnsafeToolRegistryServiceServer interface {
	mustEmbedUnimplementedToolRegistryServiceServer()
}

func RegisterToolRegistryServiceServer(s grpc.ServiceRegistrar, srv ToolRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedToolRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolRegistryService_ServiceDesc, srv)
}

func _ToolRegistryService_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolRegistryServiceServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolRegistryService_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolRegistryServiceServer).RegisterTool(ctx, req.(*RegisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolRegistryService_GetTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolRegistryServiceServer).GetTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolRegistryService_GetTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolRegistryServiceServer).GetTool(ctx, req.(*GetToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolRegistryService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolRegistryServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolRegistryService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolRegistryServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolRegistryService_RetractTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolRegistryServiceServer).RetractTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolRegistryService_RetractTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolRegistryServiceServer).RetractTool(ctx, req.(*RetractToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolRegistryService_DeleteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolRegistryServiceServer).DeleteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolRegistryService_DeleteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolRegistryServiceServer).DeleteTool(ctx, req.(*DeleteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolRegistryService_ServiceDesc is the grpc.ServiceDesc for ToolRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.ToolRegistryService",
	HandlerType: (*ToolRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTool",
			Handler:    _ToolRegistryService_RegisterTool_Handler,
		},
		{
			MethodName: "GetTool",
			Handler:    _ToolRegistryService_GetTool_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _ToolRegistryService_ListTools_Handler,
		},
		{
			MethodName: "RetractTool",
			Handler:    _ToolRegistryService_RetractTool_Handler,
		},
		{
			MethodName: "DeleteTool",
			Handler:    _ToolRegistryService_DeleteTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	DataRegistryService_RegisterData_FullMethodName = "/nodevault.v1.DataRegistryService/RegisterData"
	DataRegistryService_GetData_FullMethodName      = "/nodevault.v1.DataRegistryService/GetData"
	DataRegistryService_ListData_FullMethodName     = "/nodevault.v1.DataRegistryService/ListData"
)

// DataRegistryServiceClient is the client API for DataRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataRegistryServiceClient interface {
	RegisterData(ctx context.Context, in *DataRegisterRequest, opts ...grpc.CallOption) (*DataRegisterResponse, error)
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*RegisteredDataDefinition, error)
	ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error)
}

type dataRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataRegistryServiceClient(cc grpc.ClientConnInterface) DataRegistryServiceClient {
	return &dataRegistryServiceClient{cc}
}

func (c *dataRegistryServiceClient) RegisterData(ctx context.Context, in *DataRegisterRequest, opts ...grpc.CallOption) (*DataRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRegisterResponse)
	err := c.cc.Invoke(ctx, DataRegistryService_RegisterData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataRegistryServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*RegisteredDataDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisteredDataDefinition)
	err := c.cc.Invoke(ctx, DataRegistryService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataRegistryServiceClient) ListData(ctx context.Context, in *ListDataRequest, opts ...grpc.CallOption) (*ListDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataResponse)
	err := c.cc.Invoke(ctx, DataRegistryService_ListData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataRegistryServiceServer is the server API for DataRegistryService service.
// All implementations must embed UnimplementedDataRegistryServiceServer
// for forward compatibility.
type DataRegistryServiceServer interface {
	RegisterData(context.Context, *DataRegisterRequest) (*DataRegisterResponse, error)
	GetData(context.Context, *GetDataRequest) (*RegisteredDataDefinition, error)
	ListData(context.Context, *ListDataRequest) (*ListDataResponse, error)
	mustEmbedUnimplementedDataRegistryServiceServer()
}

// UnimplementedDataRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataRegistryServiceServer struct{}

func (UnimplementedDataRegistryServiceServer) RegisterData(context.Context, *DataRegisterRequest) (*DataRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterData not implemented")
}
func (UnimplementedDataRegistryServiceServer) GetData(context.Context, *GetDataRequest) (*RegisteredDataDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDataRegistryServiceServer) ListData(context.Context, *ListDataRequest) (*ListDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListData not implemented")
}
func (UnimplementedDataRegistryServiceServer) mustEmbedUnimplementedDataRegistryServiceServer() {}
func (UnimplementedDataRegistryServiceServer) testEmbeddedByValue()                             {}

// UnsafeDataRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataRegistryServiceServer will
// result in compilation errors.
type UnsafeDataRegistryServiceServer interface {
	mustEmbedUnimplementedDataRegistryServiceServer()
}

func RegisterDataRegistryServiceServer(s grpc.ServiceRegistrar, srv DataRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedDataRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataRegistryService_ServiceDesc, srv)
}

func _DataRegistryService_RegisterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRegistryServiceServer).RegisterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRegistryService_RegisterData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRegistryServiceServer).RegisterData(ctx, req.(*DataRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataRegistryService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRegistryServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRegistryService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRegistryServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataRegistryService_ListData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataRegistryServiceServer).ListData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataRegistryService_ListData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataRegistryServiceServer).ListData(ctx, req.(*ListDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataRegistryService_ServiceDesc is the grpc.ServiceDesc for DataRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.DataRegistryService",
	HandlerType: (*DataRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterData",
			Handler:    _DataRegistryService_RegisterData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _DataRegistryService_GetData_Handler,
		},
		{
			MethodName: "ListData",
			Handler:    _DataRegistryService_ListData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	ValidationResultService_SubmitToolCheckRecord_FullMethodName = "/nodevault.v1.ValidationResultService/SubmitToolCheckRecord"
	ValidationResultService_SubmitToolScanRecord_FullMethodName  = "/nodevault.v1.ValidationResultService/SubmitToolScanRecord"
	ValidationResultService_ListCertifiedTools_FullMethodName    = "/nodevault.v1.ValidationResultService/ListCertifiedTools"
)

// ValidationResultServiceClient is the client API for ValidationResultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationResultServiceClient interface {
	// SubmitToolCheckRecord receives a L5-a functional validation result from NodeSentinel.
	SubmitToolCheckRecord(ctx context.Context, in *ToolCheckRecordRequest, opts ...grpc.CallOption) (*SubmitRecordResponse, error)
	// SubmitToolScanRecord receives a L5-b trivy security scan result from NodeSentinel.
	SubmitToolScanRecord(ctx context.Context, in *ToolScanRecordRequest, opts ...grpc.CallOption) (*SubmitRecordResponse, error)
	// ListCertifiedTools returns all active certified tool catalog entries.
	ListCertifiedTools(ctx context.Context, in *ListCertifiedToolsRequest, opts ...grpc.CallOption) (*ListCertifiedToolsResponse, error)
}

type validationResultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationResultServiceClient(cc grpc.ClientConnInterface) ValidationResultServiceClient {
	return &validationResultServiceClient{cc}
}

func (c *validationResultServiceClient) SubmitToolCheckRecord(ctx context.Context, in *ToolCheckRecordRequest, opts ...grpc.CallOption) (*SubmitRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRecordResponse)
	err := c.cc.Invoke(ctx, ValidationResultService_SubmitToolCheckRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationResultServiceClient) SubmitToolScanRecord(ctx context.Context, in *ToolScanRecordRequest, opts ...grpc.CallOption) (*SubmitRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRecordResponse)
	err := c.cc.Invoke(ctx, ValidationResultService_SubmitToolScanRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationResultServiceClient) ListCertifiedTools(ctx context.Context, in *ListCertifiedToolsRequest, opts ...grpc.CallOption) (*ListCertifiedToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertifiedToolsResponse)
	err := c.cc.Invoke(ctx, ValidationResultService_ListCertifiedTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidationResultServiceServer is the server API for ValidationResultService service.
// All implementations must embed UnimplementedValidationResultServiceServer
// for forward compatibility.
type ValidationResultServiceServer interface {
	// SubmitToolCheckRecord receives a L5-a functional validation result from NodeSentinel.
	SubmitToolCheckRecord(context.Context, *ToolCheckRecordRequest) (*SubmitRecordResponse, error)
	// SubmitToolScanRecord receives a L5-b trivy security scan result from NodeSentinel.
	SubmitToolScanRecord(context.Context, *ToolScanRecordRequest) (*SubmitRecordResponse, error)
	// ListCertifiedTools returns all active certified tool catalog entries.
	ListCertifiedTools(context.Context, *ListCertifiedToolsRequest) (*ListCertifiedToolsResponse, error)
	mustEmbedUnimplementedValidationResultServiceServer()
}

// UnimplementedValidationResultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidationResultServiceServer struct{}

func (UnimplementedValidationResultServiceServer) SubmitToolCheckRecord(context.Context, *ToolCheckRecordRequest) (*SubmitRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitToolCheckRecord not implemented")
}
func (UnimplementedValidationResultServiceServer) SubmitToolScanRecord(context.Context, *ToolScanRecordRequest) (*SubmitRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitToolScanRecord not implemented")
}
func (UnimplementedValidationResultServiceServer) ListCertifiedTools(context.Context, *ListCertifiedToolsRequest) (*ListCertifiedToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCertifiedTools not implemented")
}
func (UnimplementedValidationResultServiceServer) mustEmbedUnimplementedValidationResultServiceServer() {
}
func (UnimplementedValidationResultServiceServer) testEmbeddedByValue() {}

// UnsafeValidationResultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationResultServiceServer will
// result in compilation errors.
type UnsafeValidationResultServiceServer interface {
	mustEmbedUnimplementedValidationResultServiceServer()
}

func RegisterValidationResultServiceServer(s grpc.ServiceRegistrar, srv ValidationResultServiceServer) {
	// If the following call panics, it indicates UnimplementedValidationResultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidationResultService_ServiceDesc, srv)
}

func _ValidationResultService_SubmitToolCheckRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolCheckRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationResultServiceServer).SubmitToolCheckRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationResultService_SubmitToolCheckRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationResultServiceServer).SubmitToolCheckRecord(ctx, req.(*ToolCheckRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationResultService_SubmitToolScanRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolScanRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationResultServiceServer).SubmitToolScanRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationResultService_SubmitToolScanRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationResultServiceServer).SubmitToolScanRecord(ctx, req.(*ToolScanRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationResultService_ListCertifiedTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertifiedToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationResultServiceServer).ListCertifiedTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationResultService_ListCertifiedTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationResultServiceServer).ListCertifiedTools(ctx, req.(*ListCertifiedToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidationResultService_ServiceDesc is the grpc.ServiceDesc for ValidationResultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidationResultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.ValidationResultService",
	HandlerType: (*ValidationResultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitToolCheckRecord",
			Handler:    _ValidationResultService_SubmitToolCheckRecord_Handler,
		},
		{
			MethodName: "SubmitToolScanRecord",
			Handler:    _ValidationResultService_SubmitToolScanRecord_Handler,
		},
		{
			MethodName: "ListCertifiedTools",
			Handler:    _ValidationResultService_ListCertifiedTools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}

const (
	PingService_Ping_FullMethodName = "/nodevault.v1.PingService/Ping"
)

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServiceClient(cc grpc.ClientConnInterface) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, PingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServiceServer is the server API for PingService service.
// All implementations must embed UnimplementedPingServiceServer
// for forward compatibility.
type PingServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedPingServiceServer()
}

// UnimplementedPingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingServiceServer struct{}

func (UnimplementedPingServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingServiceServer) mustEmbedUnimplementedPingServiceServer() {}
func (UnimplementedPingServiceServer) testEmbeddedByValue()                     {}

// UnsafePingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingServiceServer will
// result in compilation errors.
type UnsafePingServiceServer interface {
	mustEmbedUnimplementedPingServiceServer()
}

func RegisterPingServiceServer(s grpc.ServiceRegistrar, srv PingServiceServer) {
	// If the following call panics, it indicates UnimplementedPingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingService_ServiceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PingService_ServiceDesc is the grpc.ServiceDesc for PingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodevault.v1.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodevault/v1/nodevault.proto",
}
