// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nodevault.proto

package nodevaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildEventKind int32

const (
	BuildEventKind_BUILD_EVENT_KIND_UNSPECIFIED     BuildEventKind = 0
	BuildEventKind_BUILD_EVENT_KIND_LOG             BuildEventKind = 1
	BuildEventKind_BUILD_EVENT_KIND_JOB_CREATED     BuildEventKind = 2
	BuildEventKind_BUILD_EVENT_KIND_JOB_RUNNING     BuildEventKind = 3
	BuildEventKind_BUILD_EVENT_KIND_PUSH_SUCCEEDED  BuildEventKind = 4
	BuildEventKind_BUILD_EVENT_KIND_DIGEST_ACQUIRED BuildEventKind = 5
	BuildEventKind_BUILD_EVENT_KIND_SUCCEEDED       BuildEventKind = 6
	BuildEventKind_BUILD_EVENT_KIND_FAILED          BuildEventKind = 7
)

// Enum value maps for BuildEventKind.
var (
	BuildEventKind_name = map[int32]string{
		0: "BUILD_EVENT_KIND_UNSPECIFIED",
		1: "BUILD_EVENT_KIND_LOG",
		2: "BUILD_EVENT_KIND_JOB_CREATED",
		3: "BUILD_EVENT_KIND_JOB_RUNNING",
		4: "BUILD_EVENT_KIND_PUSH_SUCCEEDED",
		5: "BUILD_EVENT_KIND_DIGEST_ACQUIRED",
		6: "BUILD_EVENT_KIND_SUCCEEDED",
		7: "BUILD_EVENT_KIND_FAILED",
	}
	BuildEventKind_value = map[string]int32{
		"BUILD_EVENT_KIND_UNSPECIFIED":     0,
		"BUILD_EVENT_KIND_LOG":             1,
		"BUILD_EVENT_KIND_JOB_CREATED":     2,
		"BUILD_EVENT_KIND_JOB_RUNNING":     3,
		"BUILD_EVENT_KIND_PUSH_SUCCEEDED":  4,
		"BUILD_EVENT_KIND_DIGEST_ACQUIRED": 5,
		"BUILD_EVENT_KIND_SUCCEEDED":       6,
		"BUILD_EVENT_KIND_FAILED":          7,
	}
)

func (x BuildEventKind) Enum() *BuildEventKind {
	p := new(BuildEventKind)
	*p = x
	return p
}

func (x BuildEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_nodevault_proto_enumTypes[0].Descriptor()
}

func (BuildEventKind) Type() protoreflect.EnumType {
	return &file_nodevault_proto_enumTypes[0]
}

func (x BuildEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildEventKind.Descriptor instead.
func (BuildEventKind) EnumDescriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{0}
}

type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Shape         string                 `protobuf:"bytes,4,opt,name=shape,proto3" json:"shape,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Class         string                 `protobuf:"bytes,6,opt,name=class,proto3" json:"class,omitempty"`
	Constraints   map[string]string      `protobuf:"bytes,7,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_nodevault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{0}
}

func (x *PortSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PortSpec) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PortSpec) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *PortSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *PortSpec) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *PortSpec) GetConstraints() map[string]string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type DisplaySpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplaySpec) Reset() {
	*x = DisplaySpec{}
	mi := &file_nodevault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplaySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplaySpec) ProtoMessage() {}

func (x *DisplaySpec) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplaySpec.ProtoReflect.Descriptor instead.
func (*DisplaySpec) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{1}
}

func (x *DisplaySpec) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DisplaySpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DisplaySpec) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DisplaySpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ValidationStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phase           string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	LastValidatedAt int64                  `protobuf:"varint,2,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	Failures        []string               `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidationStatus) Reset() {
	*x = ValidationStatus{}
	mi := &file_nodevault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationStatus) ProtoMessage() {}

func (x *ValidationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationStatus.ProtoReflect.Descriptor instead.
func (*ValidationStatus) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ValidationStatus) GetLastValidatedAt() int64 {
	if x != nil {
		return x.LastValidatedAt
	}
	return 0
}

func (x *ValidationStatus) GetFailures() []string {
	if x != nil {
		return x.Failures
	}
	return nil
}

type GetPolicyBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyBundleRequest) Reset() {
	*x = GetPolicyBundleRequest{}
	mi := &file_nodevault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyBundleRequest) ProtoMessage() {}

func (x *GetPolicyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyBundleRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyBundleRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{3}
}

type PolicyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasmBytes     []byte                 `protobuf:"bytes,1,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	BuiltAt       int64                  `protobuf:"varint,3,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBundle) Reset() {
	*x = PolicyBundle{}
	mi := &file_nodevault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundle) ProtoMessage() {}

func (x *PolicyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundle.ProtoReflect.Descriptor instead.
func (*PolicyBundle) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyBundle) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

func (x *PolicyBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PolicyBundle) GetBuiltAt() int64 {
	if x != nil {
		return x.BuiltAt
	}
	return 0
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_nodevault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{5}
}

type PolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyInfo) Reset() {
	*x = PolicyInfo{}
	mi := &file_nodevault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyInfo) ProtoMessage() {}

func (x *PolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyInfo.ProtoReflect.Descriptor instead.
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyInfo) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *PolicyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PolicyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyInfo          `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	BundleVersion string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_nodevault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{7}
}

func (x *ListPoliciesResponse) GetPolicies() []*PolicyInfo {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *ListPoliciesResponse) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

type ToolSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RawSpec       string                 `protobuf:"bytes,3,opt,name=raw_spec,json=rawSpec,proto3" json:"raw_spec,omitempty"`
	RequestedAt   int64                  `protobuf:"varint,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSpecRequest) Reset() {
	*x = ToolSpecRequest{}
	mi := &file_nodevault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpecRequest) ProtoMessage() {}

func (x *ToolSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpecRequest.ProtoReflect.Descriptor instead.
func (*ToolSpecRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{8}
}

func (x *ToolSpecRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolSpecRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolSpecRequest) GetRawSpec() string {
	if x != nil {
		return x.RawSpec
	}
	return ""
}

func (x *ToolSpecRequest) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

type ResolvedToolSpecResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolSpecDigest string                 `protobuf:"bytes,1,opt,name=tool_spec_digest,json=toolSpecDigest,proto3" json:"tool_spec_digest,omitempty"`
	ToolName       string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ResolvedAt     int64                  `protobuf:"varint,4,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvedToolSpecResponse) Reset() {
	*x = ResolvedToolSpecResponse{}
	mi := &file_nodevault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedToolSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedToolSpecResponse) ProtoMessage() {}

func (x *ResolvedToolSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedToolSpecResponse.ProtoReflect.Descriptor instead.
func (*ResolvedToolSpecResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvedToolSpecResponse) GetToolSpecDigest() string {
	if x != nil {
		return x.ToolSpecDigest
	}
	return ""
}

func (x *ResolvedToolSpecResponse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ResolvedToolSpecResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedToolSpecResponse) GetResolvedAt() int64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

type BuildRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ToolDefinitionId  string                 `protobuf:"bytes,2,opt,name=tool_definition_id,json=toolDefinitionId,proto3" json:"tool_definition_id,omitempty"`
	ToolName          string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ImageUri          string                 `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	DockerfileContent string                 `protobuf:"bytes,5,opt,name=dockerfile_content,json=dockerfileContent,proto3" json:"dockerfile_content,omitempty"`
	Script            string                 `protobuf:"bytes,6,opt,name=script,proto3" json:"script,omitempty"`
	EnvironmentSpec   string                 `protobuf:"bytes,9,opt,name=environment_spec,json=environmentSpec,proto3" json:"environment_spec,omitempty"`
	Version           string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	Inputs            []*PortSpec            `protobuf:"bytes,12,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs           []*PortSpec            `protobuf:"bytes,13,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Display           *DisplaySpec           `protobuf:"bytes,14,opt,name=display,proto3" json:"display,omitempty"`
	Command           string                 `protobuf:"bytes,15,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_nodevault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{10}
}

func (x *BuildRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BuildRequest) GetToolDefinitionId() string {
	if x != nil {
		return x.ToolDefinitionId
	}
	return ""
}

func (x *BuildRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *BuildRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *BuildRequest) GetDockerfileContent() string {
	if x != nil {
		return x.DockerfileContent
	}
	return ""
}

func (x *BuildRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *BuildRequest) GetEnvironmentSpec() string {
	if x != nil {
		return x.EnvironmentSpec
	}
	return ""
}

func (x *BuildRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildRequest) GetInputs() []*PortSpec {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *BuildRequest) GetOutputs() []*PortSpec {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *BuildRequest) GetDisplay() *DisplaySpec {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *BuildRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type BuildEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          BuildEventKind         `protobuf:"varint,1,opt,name=kind,proto3,enum=nodevault.v1.BuildEventKind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_nodevault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{11}
}

func (x *BuildEvent) GetKind() BuildEventKind {
	if x != nil {
		return x.Kind
	}
	return BuildEventKind_BUILD_EVENT_KIND_UNSPECIFIED
}

func (x *BuildEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BuildEvent) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type DryRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ManifestYaml  string                 `protobuf:"bytes,2,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryRunRequest) Reset() {
	*x = DryRunRequest{}
	mi := &file_nodevault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunRequest) ProtoMessage() {}

func (x *DryRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunRequest.ProtoReflect.Descriptor instead.
func (*DryRunRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{12}
}

func (x *DryRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DryRunRequest) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

type DryRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryRunResult) Reset() {
	*x = DryRunResult{}
	mi := &file_nodevault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunResult) ProtoMessage() {}

func (x *DryRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunResult.ProtoReflect.Descriptor instead.
func (*DryRunResult) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{13}
}

func (x *DryRunResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DryRunResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SmokeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ManifestYaml  string                 `protobuf:"bytes,2,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmokeRunRequest) Reset() {
	*x = SmokeRunRequest{}
	mi := &file_nodevault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmokeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmokeRunRequest) ProtoMessage() {}

func (x *SmokeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmokeRunRequest.ProtoReflect.Descriptor instead.
func (*SmokeRunRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{14}
}

func (x *SmokeRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SmokeRunRequest) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

type SmokeRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	LogOutput     string                 `protobuf:"bytes,3,opt,name=log_output,json=logOutput,proto3" json:"log_output,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmokeRunResult) Reset() {
	*x = SmokeRunResult{}
	mi := &file_nodevault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmokeRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmokeRunResult) ProtoMessage() {}

func (x *SmokeRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmokeRunResult.ProtoReflect.Descriptor instead.
func (*SmokeRunResult) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{15}
}

func (x *SmokeRunResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SmokeRunResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SmokeRunResult) GetLogOutput() string {
	if x != nil {
		return x.LogOutput
	}
	return ""
}

func (x *SmokeRunResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RegisterToolRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ToolDefinitionId string                 `protobuf:"bytes,2,opt,name=tool_definition_id,json=toolDefinitionId,proto3" json:"tool_definition_id,omitempty"`
	ToolName         string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ImageUri         string                 `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Digest           string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	EnvironmentSpec  string                 `protobuf:"bytes,8,opt,name=environment_spec,json=environmentSpec,proto3" json:"environment_spec,omitempty"`
	Version          string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	StableRef        string                 `protobuf:"bytes,10,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	Inputs           []*PortSpec            `protobuf:"bytes,11,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs          []*PortSpec            `protobuf:"bytes,12,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Display          *DisplaySpec           `protobuf:"bytes,13,opt,name=display,proto3" json:"display,omitempty"`
	Command          string                 `protobuf:"bytes,14,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterToolRequest) Reset() {
	*x = RegisterToolRequest{}
	mi := &file_nodevault_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToolRequest) ProtoMessage() {}

func (x *RegisterToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToolRequest.ProtoReflect.Descriptor instead.
func (*RegisterToolRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterToolRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RegisterToolRequest) GetToolDefinitionId() string {
	if x != nil {
		return x.ToolDefinitionId
	}
	return ""
}

func (x *RegisterToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RegisterToolRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *RegisterToolRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegisterToolRequest) GetEnvironmentSpec() string {
	if x != nil {
		return x.EnvironmentSpec
	}
	return ""
}

func (x *RegisterToolRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterToolRequest) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *RegisterToolRequest) GetInputs() []*PortSpec {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RegisterToolRequest) GetOutputs() []*PortSpec {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *RegisterToolRequest) GetDisplay() *DisplaySpec {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *RegisterToolRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RegisterToolResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CasHash       string                    `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	Tool          *RegisteredToolDefinition `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterToolResponse) Reset() {
	*x = RegisterToolResponse{}
	mi := &file_nodevault_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToolResponse) ProtoMessage() {}

func (x *RegisterToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToolResponse.ProtoReflect.Descriptor instead.
func (*RegisterToolResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterToolResponse) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *RegisterToolResponse) GetTool() *RegisteredToolDefinition {
	if x != nil {
		return x.Tool
	}
	return nil
}

type GetToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasHash       string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolRequest) Reset() {
	*x = GetToolRequest{}
	mi := &file_nodevault_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolRequest) ProtoMessage() {}

func (x *GetToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolRequest.ProtoReflect.Descriptor instead.
func (*GetToolRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{18}
}

func (x *GetToolRequest) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StableRef     string                 `protobuf:"bytes,1,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	ArtifactKind  string                 `protobuf:"bytes,2,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_nodevault_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{19}
}

func (x *ListToolsRequest) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *ListToolsRequest) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Tools         []*RegisteredToolDefinition `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_nodevault_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{20}
}

func (x *ListToolsResponse) GetTools() []*RegisteredToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type RegisteredToolDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CasHash          string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	ToolDefinitionId string                 `protobuf:"bytes,2,opt,name=tool_definition_id,json=toolDefinitionId,proto3" json:"tool_definition_id,omitempty"`
	ToolName         string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ImageUri         string                 `protobuf:"bytes,4,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Digest           string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	RegisteredAt     int64                  `protobuf:"varint,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	EnvironmentSpec  string                 `protobuf:"bytes,9,opt,name=environment_spec,json=environmentSpec,proto3" json:"environment_spec,omitempty"`
	Version          string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version,omitempty"`
	StableRef        string                 `protobuf:"bytes,11,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	Inputs           []*PortSpec            `protobuf:"bytes,12,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs          []*PortSpec            `protobuf:"bytes,13,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Display          *DisplaySpec           `protobuf:"bytes,14,opt,name=display,proto3" json:"display,omitempty"`
	LifecyclePhase   string                 `protobuf:"bytes,15,opt,name=lifecycle_phase,json=lifecyclePhase,proto3" json:"lifecycle_phase,omitempty"`
	Validation       *ValidationStatus      `protobuf:"bytes,16,opt,name=validation,proto3" json:"validation,omitempty"`
	Command          string                 `protobuf:"bytes,17,opt,name=command,proto3" json:"command,omitempty"`
	IntegrityHealth  string                 `protobuf:"bytes,18,opt,name=integrity_health,json=integrityHealth,proto3" json:"integrity_health,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisteredToolDefinition) Reset() {
	*x = RegisteredToolDefinition{}
	mi := &file_nodevault_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredToolDefinition) ProtoMessage() {}

func (x *RegisteredToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredToolDefinition.ProtoReflect.Descriptor instead.
func (*RegisteredToolDefinition) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{21}
}

func (x *RegisteredToolDefinition) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *RegisteredToolDefinition) GetToolDefinitionId() string {
	if x != nil {
		return x.ToolDefinitionId
	}
	return ""
}

func (x *RegisteredToolDefinition) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RegisteredToolDefinition) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *RegisteredToolDefinition) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegisteredToolDefinition) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *RegisteredToolDefinition) GetEnvironmentSpec() string {
	if x != nil {
		return x.EnvironmentSpec
	}
	return ""
}

func (x *RegisteredToolDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisteredToolDefinition) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *RegisteredToolDefinition) GetInputs() []*PortSpec {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RegisteredToolDefinition) GetOutputs() []*PortSpec {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *RegisteredToolDefinition) GetDisplay() *DisplaySpec {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *RegisteredToolDefinition) GetLifecyclePhase() string {
	if x != nil {
		return x.LifecyclePhase
	}
	return ""
}

func (x *RegisteredToolDefinition) GetValidation() *ValidationStatus {
	if x != nil {
		return x.Validation
	}
	return nil
}

func (x *RegisteredToolDefinition) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RegisteredToolDefinition) GetIntegrityHealth() string {
	if x != nil {
		return x.IntegrityHealth
	}
	return ""
}

type RetractToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasHash       string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractToolRequest) Reset() {
	*x = RetractToolRequest{}
	mi := &file_nodevault_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractToolRequest) ProtoMessage() {}

func (x *RetractToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractToolRequest.ProtoReflect.Descriptor instead.
func (*RetractToolRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{22}
}

func (x *RetractToolRequest) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *RetractToolRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RetractToolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CasHash        string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	LifecyclePhase string                 `protobuf:"bytes,2,opt,name=lifecycle_phase,json=lifecyclePhase,proto3" json:"lifecycle_phase,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetractToolResponse) Reset() {
	*x = RetractToolResponse{}
	mi := &file_nodevault_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractToolResponse) ProtoMessage() {}

func (x *RetractToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractToolResponse.ProtoReflect.Descriptor instead.
func (*RetractToolResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{23}
}

func (x *RetractToolResponse) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *RetractToolResponse) GetLifecyclePhase() string {
	if x != nil {
		return x.LifecyclePhase
	}
	return ""
}

type DeleteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasHash       string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteToolRequest) Reset() {
	*x = DeleteToolRequest{}
	mi := &file_nodevault_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolRequest) ProtoMessage() {}

func (x *DeleteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolRequest.ProtoReflect.Descriptor instead.
func (*DeleteToolRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteToolRequest) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *DeleteToolRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteToolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CasHash        string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	LifecyclePhase string                 `protobuf:"bytes,2,opt,name=lifecycle_phase,json=lifecyclePhase,proto3" json:"lifecycle_phase,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteToolResponse) Reset() {
	*x = DeleteToolResponse{}
	mi := &file_nodevault_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteToolResponse) ProtoMessage() {}

func (x *DeleteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteToolResponse.ProtoReflect.Descriptor instead.
func (*DeleteToolResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteToolResponse) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *DeleteToolResponse) GetLifecyclePhase() string {
	if x != nil {
		return x.LifecyclePhase
	}
	return ""
}

type DataRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DataName      string                 `protobuf:"bytes,2,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	SourceUri     string                 `protobuf:"bytes,6,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	StorageUri    string                 `protobuf:"bytes,8,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	StableRef     string                 `protobuf:"bytes,9,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	Display       *DisplaySpec           `protobuf:"bytes,10,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRegisterRequest) Reset() {
	*x = DataRegisterRequest{}
	mi := &file_nodevault_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRegisterRequest) ProtoMessage() {}

func (x *DataRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRegisterRequest.ProtoReflect.Descriptor instead.
func (*DataRegisterRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{26}
}

func (x *DataRegisterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DataRegisterRequest) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

func (x *DataRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DataRegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataRegisterRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DataRegisterRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *DataRegisterRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *DataRegisterRequest) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *DataRegisterRequest) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *DataRegisterRequest) GetDisplay() *DisplaySpec {
	if x != nil {
		return x.Display
	}
	return nil
}

type DataRegisterResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	CasHash       string                    `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	Data          *RegisteredDataDefinition `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRegisterResponse) Reset() {
	*x = DataRegisterResponse{}
	mi := &file_nodevault_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRegisterResponse) ProtoMessage() {}

func (x *DataRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRegisterResponse.ProtoReflect.Descriptor instead.
func (*DataRegisterResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{27}
}

func (x *DataRegisterResponse) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *DataRegisterResponse) GetData() *RegisteredDataDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasHash       string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_nodevault_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{28}
}

func (x *GetDataRequest) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

type ListDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StableRef     string                 `protobuf:"bytes,1,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataRequest) Reset() {
	*x = ListDataRequest{}
	mi := &file_nodevault_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataRequest) ProtoMessage() {}

func (x *ListDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataRequest.ProtoReflect.Descriptor instead.
func (*ListDataRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{29}
}

func (x *ListDataRequest) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

type ListDataResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Data          []*RegisteredDataDefinition `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataResponse) Reset() {
	*x = ListDataResponse{}
	mi := &file_nodevault_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataResponse) ProtoMessage() {}

func (x *ListDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataResponse.ProtoReflect.Descriptor instead.
func (*ListDataResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{30}
}

func (x *ListDataResponse) GetData() []*RegisteredDataDefinition {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisteredDataDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CasHash         string                 `protobuf:"bytes,1,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	DataName        string                 `protobuf:"bytes,2,opt,name=data_name,json=dataName,proto3" json:"data_name,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Format          string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	SourceUri       string                 `protobuf:"bytes,6,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	Checksum        string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	StorageUri      string                 `protobuf:"bytes,8,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	StableRef       string                 `protobuf:"bytes,9,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	Display         *DisplaySpec           `protobuf:"bytes,10,opt,name=display,proto3" json:"display,omitempty"`
	RegisteredAt    int64                  `protobuf:"varint,11,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LifecyclePhase  string                 `protobuf:"bytes,12,opt,name=lifecycle_phase,json=lifecyclePhase,proto3" json:"lifecycle_phase,omitempty"`
	IntegrityHealth string                 `protobuf:"bytes,13,opt,name=integrity_health,json=integrityHealth,proto3" json:"integrity_health,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisteredDataDefinition) Reset() {
	*x = RegisteredDataDefinition{}
	mi := &file_nodevault_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredDataDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredDataDefinition) ProtoMessage() {}

func (x *RegisteredDataDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredDataDefinition.ProtoReflect.Descriptor instead.
func (*RegisteredDataDefinition) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{31}
}

func (x *RegisteredDataDefinition) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *RegisteredDataDefinition) GetDataName() string {
	if x != nil {
		return x.DataName
	}
	return ""
}

func (x *RegisteredDataDefinition) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisteredDataDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisteredDataDefinition) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RegisteredDataDefinition) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *RegisteredDataDefinition) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RegisteredDataDefinition) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *RegisteredDataDefinition) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *RegisteredDataDefinition) GetDisplay() *DisplaySpec {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *RegisteredDataDefinition) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *RegisteredDataDefinition) GetLifecyclePhase() string {
	if x != nil {
		return x.LifecyclePhase
	}
	return ""
}

func (x *RegisteredDataDefinition) GetIntegrityHealth() string {
	if x != nil {
		return x.IntegrityHealth
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_nodevault_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{32}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_nodevault_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodevault_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_nodevault_proto_rawDescGZIP(), []int{33}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_nodevault_proto protoreflect.FileDescriptor

const file_nodevault_proto_rawDesc = "" +
	"\n" +
	"\x0fnodevault.proto\x12\fnodevault.v1\"\x9d\x02\n" +
	"\bPortSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05shape\x18\x04 \x01(\tR\x05shape\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x14\n" +
	"\x05class\x18\x06 \x01(\tR\x05class\x12I\n" +
	"\vconstraints\x18\a \x03(\v2'.nodevault.v1.PortSpec.ConstraintsEntryR\vconstraints\x1a>\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\vDisplaySpec\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"p\n" +
	"\x10ValidationStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12*\n" +
	"\x11last_validated_at\x18\x02 \x01(\x03R\x0flastValidatedAt\x12\x1a\n" +
	"\bfailures\x18\x03 \x03(\tR\bfailures\"\x18\n" +
	"\x16GetPolicyBundleRequest\"b\n" +
	"\fPolicyBundle\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\x01 \x01(\fR\twasmBytes\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bbuilt_at\x18\x03 \x01(\x03R\abuiltAt\"\x15\n" +
	"\x13ListPoliciesRequest\"u\n" +
	"\n" +
	"PolicyInfo\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"s\n" +
	"\x14ListPoliciesResponse\x124\n" +
	"\bpolicies\x18\x01 \x03(\v2\x18.nodevault.v1.PolicyInfoR\bpolicies\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\"\x86\x01\n" +
	"\x0fToolSpecRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\braw_spec\x18\x03 \x01(\tR\arawSpec\x12!\n" +
	"\frequested_at\x18\x04 \x01(\x03R\vrequestedAt\"\x9c\x01\n" +
	"\x18ResolvedToolSpecResponse\x12(\n" +
	"\x10tool_spec_digest\x18\x01 \x01(\tR\x0etoolSpecDigest\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vresolved_at\x18\x04 \x01(\x03R\n" +
	"resolvedAt\"\xf9\x03\n" +
	"\fBuildRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x12tool_definition_id\x18\x02 \x01(\tR\x10toolDefinitionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1b\n" +
	"\timage_uri\x18\x04 \x01(\tR\bimageUri\x12-\n" +
	"\x12dockerfile_content\x18\x05 \x01(\tR\x11dockerfileContent\x12\x16\n" +
	"\x06script\x18\x06 \x01(\tR\x06script\x12)\n" +
	"\x10environment_spec\x18\t \x01(\tR\x0fenvironmentSpec\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12.\n" +
	"\x06inputs\x18\f \x03(\v2\x16.nodevault.v1.PortSpecR\x06inputs\x120\n" +
	"\aoutputs\x18\r \x03(\v2\x16.nodevault.v1.PortSpecR\aoutputs\x123\n" +
	"\adisplay\x18\x0e \x01(\v2\x19.nodevault.v1.DisplaySpecR\adisplay\x12\x18\n" +
	"\acommand\x18\x0f \x01(\tR\acommandJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\vinput_namesR\foutput_names\"\x8e\x01\n" +
	"\n" +
	"BuildEvent\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.nodevault.v1.BuildEventKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"S\n" +
	"\rDryRunRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmanifest_yaml\x18\x02 \x01(\tR\fmanifestYaml\"M\n" +
	"\fDryRunResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"U\n" +
	"\x0fSmokeRunRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmanifest_yaml\x18\x02 \x01(\tR\fmanifestYaml\"\x8b\x01\n" +
	"\x0eSmokeRunResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"log_output\x18\x03 \x01(\tR\tlogOutput\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xf0\x03\n" +
	"\x13RegisterToolRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12,\n" +
	"\x12tool_definition_id\x18\x02 \x01(\tR\x10toolDefinitionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1b\n" +
	"\timage_uri\x18\x04 \x01(\tR\bimageUri\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12)\n" +
	"\x10environment_spec\x18\b \x01(\tR\x0fenvironmentSpec\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\n" +
	" \x01(\tR\tstableRef\x12.\n" +
	"\x06inputs\x18\v \x03(\v2\x16.nodevault.v1.PortSpecR\x06inputs\x120\n" +
	"\aoutputs\x18\f \x03(\v2\x16.nodevault.v1.PortSpecR\aoutputs\x123\n" +
	"\adisplay\x18\r \x01(\v2\x19.nodevault.v1.DisplaySpecR\adisplay\x12\x18\n" +
	"\acommand\x18\x0e \x01(\tR\acommandJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\vinput_namesR\foutput_names\"m\n" +
	"\x14RegisterToolResponse\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12:\n" +
	"\x04tool\x18\x02 \x01(\v2&.nodevault.v1.RegisteredToolDefinitionR\x04tool\"+\n" +
	"\x0eGetToolRequest\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\"V\n" +
	"\x10ListToolsRequest\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\x01 \x01(\tR\tstableRef\x12#\n" +
	"\rartifact_kind\x18\x02 \x01(\tR\fartifactKind\"Q\n" +
	"\x11ListToolsResponse\x12<\n" +
	"\x05tools\x18\x01 \x03(\v2&.nodevault.v1.RegisteredToolDefinitionR\x05tools\"\xaa\x05\n" +
	"\x18RegisteredToolDefinition\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12,\n" +
	"\x12tool_definition_id\x18\x02 \x01(\tR\x10toolDefinitionId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1b\n" +
	"\timage_uri\x18\x04 \x01(\tR\bimageUri\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12#\n" +
	"\rregistered_at\x18\b \x01(\x03R\fregisteredAt\x12)\n" +
	"\x10environment_spec\x18\t \x01(\tR\x0fenvironmentSpec\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\v \x01(\tR\tstableRef\x12.\n" +
	"\x06inputs\x18\f \x03(\v2\x16.nodevault.v1.PortSpecR\x06inputs\x120\n" +
	"\aoutputs\x18\r \x03(\v2\x16.nodevault.v1.PortSpecR\aoutputs\x123\n" +
	"\adisplay\x18\x0e \x01(\v2\x19.nodevault.v1.DisplaySpecR\adisplay\x12'\n" +
	"\x0flifecycle_phase\x18\x0f \x01(\tR\x0elifecyclePhase\x12>\n" +
	"\n" +
	"validation\x18\x10 \x01(\v2\x1e.nodevault.v1.ValidationStatusR\n" +
	"validation\x12\x18\n" +
	"\acommand\x18\x11 \x01(\tR\acommand\x12)\n" +
	"\x10integrity_health\x18\x12 \x01(\tR\x0fintegrityHealthJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\vinput_namesR\foutput_names\"G\n" +
	"\x12RetractToolRequest\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Y\n" +
	"\x13RetractToolResponse\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12'\n" +
	"\x0flifecycle_phase\x18\x02 \x01(\tR\x0elifecyclePhase\"F\n" +
	"\x11DeleteToolRequest\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"X\n" +
	"\x12DeleteToolResponse\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12'\n" +
	"\x0flifecycle_phase\x18\x02 \x01(\tR\x0elifecyclePhase\"\xd5\x02\n" +
	"\x13DataRegisterRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tdata_name\x18\x02 \x01(\tR\bdataName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x06 \x01(\tR\tsourceUri\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1f\n" +
	"\vstorage_uri\x18\b \x01(\tR\n" +
	"storageUri\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\t \x01(\tR\tstableRef\x123\n" +
	"\adisplay\x18\n" +
	" \x01(\v2\x19.nodevault.v1.DisplaySpecR\adisplay\"m\n" +
	"\x14DataRegisterResponse\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12:\n" +
	"\x04data\x18\x02 \x01(\v2&.nodevault.v1.RegisteredDataDefinitionR\x04data\"+\n" +
	"\x0eGetDataRequest\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\"0\n" +
	"\x0fListDataRequest\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\x01 \x01(\tR\tstableRef\"N\n" +
	"\x10ListDataResponse\x12:\n" +
	"\x04data\x18\x01 \x03(\v2&.nodevault.v1.RegisteredDataDefinitionR\x04data\"\xcf\x03\n" +
	"\x18RegisteredDataDefinition\x12\x19\n" +
	"\bcas_hash\x18\x01 \x01(\tR\acasHash\x12\x1b\n" +
	"\tdata_name\x18\x02 \x01(\tR\bdataName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x06 \x01(\tR\tsourceUri\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1f\n" +
	"\vstorage_uri\x18\b \x01(\tR\n" +
	"storageUri\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\t \x01(\tR\tstableRef\x123\n" +
	"\adisplay\x18\n" +
	" \x01(\v2\x19.nodevault.v1.DisplaySpecR\adisplay\x12#\n" +
	"\rregistered_at\x18\v \x01(\x03R\fregisteredAt\x12'\n" +
	"\x0flifecycle_phase\x18\f \x01(\tR\x0elifecyclePhase\x12)\n" +
	"\x10integrity_health\x18\r \x01(\tR\x0fintegrityHealth\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId*\x98\x02\n" +
	"\x0eBuildEventKind\x12 \n" +
	"\x1cBUILD_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUILD_EVENT_KIND_LOG\x10\x01\x12 \n" +
	"\x1cBUILD_EVENT_KIND_JOB_CREATED\x10\x02\x12 \n" +
	"\x1cBUILD_EVENT_KIND_JOB_RUNNING\x10\x03\x12#\n" +
	"\x1fBUILD_EVENT_KIND_PUSH_SUCCEEDED\x10\x04\x12$\n" +
	" BUILD_EVENT_KIND_DIGEST_ACQUIRED\x10\x05\x12\x1e\n" +
	"\x1aBUILD_EVENT_KIND_SUCCEEDED\x10\x06\x12\x1b\n" +
	"\x17BUILD_EVENT_KIND_FAILED\x10\a2\xbb\x01\n" +
	"\rPolicyService\x12S\n" +
	"\x0fGetPolicyBundle\x12$.nodevault.v1.GetPolicyBundleRequest\x1a\x1a.nodevault.v1.PolicyBundle\x12U\n" +
	"\fListPolicies\x12!.nodevault.v1.ListPoliciesRequest\x1a\".nodevault.v1.ListPoliciesResponse2\xb4\x01\n" +
	"\fBuildService\x12J\n" +
	"\x10BuildAndRegister\x12\x1a.nodevault.v1.BuildRequest\x1a\x18.nodevault.v1.BuildEvent0\x01\x12X\n" +
	"\x0fResolveToolSpec\x12\x1d.nodevault.v1.ToolSpecRequest\x1a&.nodevault.v1.ResolvedToolSpecResponse2\x9d\x01\n" +
	"\x0fValidateService\x12A\n" +
	"\x06DryRun\x12\x1b.nodevault.v1.DryRunRequest\x1a\x1a.nodevault.v1.DryRunResult\x12G\n" +
	"\bSmokeRun\x12\x1d.nodevault.v1.SmokeRunRequest\x1a\x1c.nodevault.v1.SmokeRunResult2\xb0\x03\n" +
	"\x13ToolRegistryService\x12U\n" +
	"\fRegisterTool\x12!.nodevault.v1.RegisterToolRequest\x1a\".nodevault.v1.RegisterToolResponse\x12O\n" +
	"\aGetTool\x12\x1c.nodevault.v1.GetToolRequest\x1a&.nodevault.v1.RegisteredToolDefinition\x12L\n" +
	"\tListTools\x12\x1e.nodevault.v1.ListToolsRequest\x1a\x1f.nodevault.v1.ListToolsResponse\x12R\n" +
	"\vRetractTool\x12 .nodevault.v1.RetractToolRequest\x1a!.nodevault.v1.RetractToolResponse\x12O\n" +
	"\n" +
	"DeleteTool\x12\x1f.nodevault.v1.DeleteToolRequest\x1a .nodevault.v1.DeleteToolResponse2\x88\x02\n" +
	"\x13DataRegistryService\x12U\n" +
	"\fRegisterData\x12!.nodevault.v1.DataRegisterRequest\x1a\".nodevault.v1.DataRegisterResponse\x12O\n" +
	"\aGetData\x12\x1c.nodevault.v1.GetDataRequest\x1a&.nodevault.v1.RegisteredDataDefinition\x12I\n" +
	"\bListData\x12\x1d.nodevault.v1.ListDataRequest\x1a\x1e.nodevault.v1.ListDataResponse2L\n" +
	"\vPingService\x12=\n" +
	"\x04Ping\x12\x19.nodevault.v1.PingRequest\x1a\x1a.nodevault.v1.PingResponseB?Z=github.com/HeaInSeo/NodeVault/protos/nodevault/v1;nodevaultv1b\x06proto3"

var (
	file_nodevault_proto_rawDescOnce sync.Once
	file_nodevault_proto_rawDescData []byte
)

func file_nodevault_proto_rawDescGZIP() []byte {
	file_nodevault_proto_rawDescOnce.Do(func() {
		file_nodevault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodevault_proto_rawDesc), len(file_nodevault_proto_rawDesc)))
	})
	return file_nodevault_proto_rawDescData
}

var file_nodevault_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodevault_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_nodevault_proto_goTypes = []any{
	(BuildEventKind)(0),              // 0: nodevault.v1.BuildEventKind
	(*PortSpec)(nil),                 // 1: nodevault.v1.PortSpec
	(*DisplaySpec)(nil),              // 2: nodevault.v1.DisplaySpec
	(*ValidationStatus)(nil),         // 3: nodevault.v1.ValidationStatus
	(*GetPolicyBundleRequest)(nil),   // 4: nodevault.v1.GetPolicyBundleRequest
	(*PolicyBundle)(nil),             // 5: nodevault.v1.PolicyBundle
	(*ListPoliciesRequest)(nil),      // 6: nodevault.v1.ListPoliciesRequest
	(*PolicyInfo)(nil),               // 7: nodevault.v1.PolicyInfo
	(*ListPoliciesResponse)(nil),     // 8: nodevault.v1.ListPoliciesResponse
	(*ToolSpecRequest)(nil),          // 9: nodevault.v1.ToolSpecRequest
	(*ResolvedToolSpecResponse)(nil), // 10: nodevault.v1.ResolvedToolSpecResponse
	(*BuildRequest)(nil),             // 11: nodevault.v1.BuildRequest
	(*BuildEvent)(nil),               // 12: nodevault.v1.BuildEvent
	(*DryRunRequest)(nil),            // 13: nodevault.v1.DryRunRequest
	(*DryRunResult)(nil),             // 14: nodevault.v1.DryRunResult
	(*SmokeRunRequest)(nil),          // 15: nodevault.v1.SmokeRunRequest
	(*SmokeRunResult)(nil),           // 16: nodevault.v1.SmokeRunResult
	(*RegisterToolRequest)(nil),      // 17: nodevault.v1.RegisterToolRequest
	(*RegisterToolResponse)(nil),     // 18: nodevault.v1.RegisterToolResponse
	(*GetToolRequest)(nil),           // 19: nodevault.v1.GetToolRequest
	(*ListToolsRequest)(nil),         // 20: nodevault.v1.ListToolsRequest
	(*ListToolsResponse)(nil),        // 21: nodevault.v1.ListToolsResponse
	(*RegisteredToolDefinition)(nil), // 22: nodevault.v1.RegisteredToolDefinition
	(*RetractToolRequest)(nil),       // 23: nodevault.v1.RetractToolRequest
	(*RetractToolResponse)(nil),      // 24: nodevault.v1.RetractToolResponse
	(*DeleteToolRequest)(nil),        // 25: nodevault.v1.DeleteToolRequest
	(*DeleteToolResponse)(nil),       // 26: nodevault.v1.DeleteToolResponse
	(*DataRegisterRequest)(nil),      // 27: nodevault.v1.DataRegisterRequest
	(*DataRegisterResponse)(nil),     // 28: nodevault.v1.DataRegisterResponse
	(*GetDataRequest)(nil),           // 29: nodevault.v1.GetDataRequest
	(*ListDataRequest)(nil),          // 30: nodevault.v1.ListDataRequest
	(*ListDataResponse)(nil),         // 31: nodevault.v1.ListDataResponse
	(*RegisteredDataDefinition)(nil), // 32: nodevault.v1.RegisteredDataDefinition
	(*PingRequest)(nil),              // 33: nodevault.v1.PingRequest
	(*PingResponse)(nil),             // 34: nodevault.v1.PingResponse
	nil,                              // 35: nodevault.v1.PortSpec.ConstraintsEntry
}
var file_nodevault_proto_depIdxs = []int32{
	35, // 0: nodevault.v1.PortSpec.constraints:type_name -> nodevault.v1.PortSpec.ConstraintsEntry
	7,  // 1: nodevault.v1.ListPoliciesResponse.policies:type_name -> nodevault.v1.PolicyInfo
	1,  // 2: nodevault.v1.BuildRequest.inputs:type_name -> nodevault.v1.PortSpec
	1,  // 3: nodevault.v1.BuildRequest.outputs:type_name -> nodevault.v1.PortSpec
	2,  // 4: nodevault.v1.BuildRequest.display:type_name -> nodevault.v1.DisplaySpec
	0,  // 5: nodevault.v1.BuildEvent.kind:type_name -> nodevault.v1.BuildEventKind
	1,  // 6: nodevault.v1.RegisterToolRequest.inputs:type_name -> nodevault.v1.PortSpec
	1,  // 7: nodevault.v1.RegisterToolRequest.outputs:type_name -> nodevault.v1.PortSpec
	2,  // 8: nodevault.v1.RegisterToolRequest.display:type_name -> nodevault.v1.DisplaySpec
	22, // 9: nodevault.v1.RegisterToolResponse.tool:type_name -> nodevault.v1.RegisteredToolDefinition
	22, // 10: nodevault.v1.ListToolsResponse.tools:type_name -> nodevault.v1.RegisteredToolDefinition
	1,  // 11: nodevault.v1.RegisteredToolDefinition.inputs:type_name -> nodevault.v1.PortSpec
	1,  // 12: nodevault.v1.RegisteredToolDefinition.outputs:type_name -> nodevault.v1.PortSpec
	2,  // 13: nodevault.v1.RegisteredToolDefinition.display:type_name -> nodevault.v1.DisplaySpec
	3,  // 14: nodevault.v1.RegisteredToolDefinition.validation:type_name -> nodevault.v1.ValidationStatus
	2,  // 15: nodevault.v1.DataRegisterRequest.display:type_name -> nodevault.v1.DisplaySpec
	32, // 16: nodevault.v1.DataRegisterResponse.data:type_name -> nodevault.v1.RegisteredDataDefinition
	32, // 17: nodevault.v1.ListDataResponse.data:type_name -> nodevault.v1.RegisteredDataDefinition
	2,  // 18: nodevault.v1.RegisteredDataDefinition.display:type_name -> nodevault.v1.DisplaySpec
	4,  // 19: nodevault.v1.PolicyService.GetPolicyBundle:input_type -> nodevault.v1.GetPolicyBundleRequest
	6,  // 20: nodevault.v1.PolicyService.ListPolicies:input_type -> nodevault.v1.ListPoliciesRequest
	11, // 21: nodevault.v1.BuildService.BuildAndRegister:input_type -> nodevault.v1.BuildRequest
	9,  // 22: nodevault.v1.BuildService.ResolveToolSpec:input_type -> nodevault.v1.ToolSpecRequest
	13, // 23: nodevault.v1.ValidateService.DryRun:input_type -> nodevault.v1.DryRunRequest
	15, // 24: nodevault.v1.ValidateService.SmokeRun:input_type -> nodevault.v1.SmokeRunRequest
	17, // 25: nodevault.v1.ToolRegistryService.RegisterTool:input_type -> nodevault.v1.RegisterToolRequest
	19, // 26: nodevault.v1.ToolRegistryService.GetTool:input_type -> nodevault.v1.GetToolRequest
	20, // 27: nodevault.v1.ToolRegistryService.ListTools:input_type -> nodevault.v1.ListToolsRequest
	23, // 28: nodevault.v1.ToolRegistryService.RetractTool:input_type -> nodevault.v1.RetractToolRequest
	25, // 29: nodevault.v1.ToolRegistryService.DeleteTool:input_type -> nodevault.v1.DeleteToolRequest
	27, // 30: nodevault.v1.DataRegistryService.RegisterData:input_type -> nodevault.v1.DataRegisterRequest
	29, // 31: nodevault.v1.DataRegistryService.GetData:input_type -> nodevault.v1.GetDataRequest
	30, // 32: nodevault.v1.DataRegistryService.ListData:input_type -> nodevault.v1.ListDataRequest
	33, // 33: nodevault.v1.PingService.Ping:input_type -> nodevault.v1.PingRequest
	5,  // 34: nodevault.v1.PolicyService.GetPolicyBundle:output_type -> nodevault.v1.PolicyBundle
	8,  // 35: nodevault.v1.PolicyService.ListPolicies:output_type -> nodevault.v1.ListPoliciesResponse
	12, // 36: nodevault.v1.BuildService.BuildAndRegister:output_type -> nodevault.v1.BuildEvent
	10, // 37: nodevault.v1.BuildService.ResolveToolSpec:output_type -> nodevault.v1.ResolvedToolSpecResponse
	14, // 38: nodevault.v1.ValidateService.DryRun:output_type -> nodevault.v1.DryRunResult
	16, // 39: nodevault.v1.ValidateService.SmokeRun:output_type -> nodevault.v1.SmokeRunResult
	18, // 40: nodevault.v1.ToolRegistryService.RegisterTool:output_type -> nodevault.v1.RegisterToolResponse
	22, // 41: nodevault.v1.ToolRegistryService.GetTool:output_type -> nodevault.v1.RegisteredToolDefinition
	21, // 42: nodevault.v1.ToolRegistryService.ListTools:output_type -> nodevault.v1.ListToolsResponse
	24, // 43: nodevault.v1.ToolRegistryService.RetractTool:output_type -> nodevault.v1.RetractToolResponse
	26, // 44: nodevault.v1.ToolRegistryService.DeleteTool:output_type -> nodevault.v1.DeleteToolResponse
	28, // 45: nodevault.v1.DataRegistryService.RegisterData:output_type -> nodevault.v1.DataRegisterResponse
	32, // 46: nodevault.v1.DataRegistryService.GetData:output_type -> nodevault.v1.RegisteredDataDefinition
	31, // 47: nodevault.v1.DataRegistryService.ListData:output_type -> nodevault.v1.ListDataResponse
	34, // 48: nodevault.v1.PingService.Ping:output_type -> nodevault.v1.PingResponse
	34, // [34:49] is the sub-list for method output_type
	19, // [19:34] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_nodevault_proto_init() }
func file_nodevault_proto_init() {
	if File_nodevault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodevault_proto_rawDesc), len(file_nodevault_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_nodevault_proto_goTypes,
		DependencyIndexes: file_nodevault_proto_depIdxs,
		EnumInfos:         file_nodevault_proto_enumTypes,
		MessageInfos:      file_nodevault_proto_msgTypes,
	}.Build()
	File_nodevault_proto = out.File
	file_nodevault_proto_goTypes = nil
	file_nodevault_proto_depIdxs = nil
}
