// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: volres/ichthys/v1/volres_service.proto

package volresv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeRef     string                 `protobuf:"bytes,1,opt,name=volume_ref,json=volumeRef,proto3" json:"volume_ref,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	RecordCount   uint64                 `protobuf:"varint,5,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	ModTime       int64                  `protobuf:"varint,6,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Root          *VolumeResource        `protobuf:"bytes,8,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeManifest) Reset() {
	*x = VolumeManifest{}
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeManifest) ProtoMessage() {}

func (x *VolumeManifest) ProtoReflect() protoreflect.Message {
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeManifest.ProtoReflect.Descriptor instead.
func (*VolumeManifest) Descriptor() ([]byte, []int) {
	return file_volres_ichthys_v1_volres_service_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeManifest) GetVolumeRef() string {
	if x != nil {
		return x.VolumeRef
	}
	return ""
}

func (x *VolumeManifest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *VolumeManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VolumeManifest) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *VolumeManifest) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *VolumeManifest) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *VolumeManifest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *VolumeManifest) GetRoot() *VolumeResource {
	if x != nil {
		return x.Root
	}
	return nil
}

type VolumeResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basename      string                 `protobuf:"bytes,1,opt,name=basename,proto3" json:"basename,omitempty"`
	FullPath      string                 `protobuf:"bytes,2,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Children      []*VolumeResource      `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeResource) Reset() {
	*x = VolumeResource{}
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResource) ProtoMessage() {}

func (x *VolumeResource) ProtoReflect() protoreflect.Message {
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResource.ProtoReflect.Descriptor instead.
func (*VolumeResource) Descriptor() ([]byte, []int) {
	return file_volres_ichthys_v1_volres_service_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeResource) GetBasename() string {
	if x != nil {
		return x.Basename
	}
	return ""
}

func (x *VolumeResource) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *VolumeResource) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *VolumeResource) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VolumeResource) GetChildren() []*VolumeResource {
	if x != nil {
		return x.Children
	}
	return nil
}

type VolumeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeManifest      `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeList) Reset() {
	*x = VolumeList{}
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeList) ProtoMessage() {}

func (x *VolumeList) ProtoReflect() protoreflect.Message {
	mi := &file_volres_ichthys_v1_volres_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeList.ProtoReflect.Descriptor instead.
func (*VolumeList) Descriptor() ([]byte, []int) {
	return file_volres_ichthys_v1_volres_service_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeList) GetVolumes() []*VolumeManifest {
	if x != nil {
		return x.Volumes
	}
	return nil
}

var File_volres_ichthys_v1_volres_service_proto protoreflect.FileDescriptor

const file_volres_ichthys_v1_volres_service_proto_rawDesc = "" +
	"\n" +
	"&volres/ichthys/v1/volres_service.proto\x12\aichthys\"\x8a\x03\n" +
	"\x0eVolumeManifest\x12\x1d\n" +
	"\n" +
	"volume_ref\x18\x01 \x01(\tR\tvolumeRef\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x04R\ttotalSize\x12!\n" +
	"\frecord_count\x18\x05 \x01(\x04R\vrecordCount\x12\x19\n" +
	"\bmod_time\x18\x06 \x01(\x03R\amodTime\x12J\n" +
	"\vannotations\x18\a \x03(\v2(.ichthys.VolumeManifest.AnnotationsEntryR\vannotations\x12+\n" +
	"\x04root\x18\b \x01(\v2\x17.ichthys.VolumeResourceR\x04root\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x0eVolumeResource\x12\x1a\n" +
	"\bbasename\x18\x01 \x01(\tR\bbasename\x12\x1b\n" +
	"\tfull_path\x18\x02 \x01(\tR\bfullPath\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x123\n" +
	"\bchildren\x18\x05 \x03(\v2\x17.ichthys.VolumeResourceR\bchildren\"?\n" +
	"\n" +
	"VolumeList\x121\n" +
	"\avolumes\x18\x01 \x03(\v2\x17.ichthys.VolumeManifestR\avolumesBAZ?github.com/HeaInSeo/NodeForge/protos/volres/ichthys/v1;volresv1b\x06proto3"

var (
	file_volres_ichthys_v1_volres_service_proto_rawDescOnce sync.Once
	file_volres_ichthys_v1_volres_service_proto_rawDescData []byte
)

func file_volres_ichthys_v1_volres_service_proto_rawDescGZIP() []byte {
	file_volres_ichthys_v1_volres_service_proto_rawDescOnce.Do(func() {
		file_volres_ichthys_v1_volres_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volres_ichthys_v1_volres_service_proto_rawDesc), len(file_volres_ichthys_v1_volres_service_proto_rawDesc)))
	})
	return file_volres_ichthys_v1_volres_service_proto_rawDescData
}

var file_volres_ichthys_v1_volres_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_volres_ichthys_v1_volres_service_proto_goTypes = []any{
	(*VolumeManifest)(nil), // 0: ichthys.VolumeManifest
	(*VolumeResource)(nil), // 1: ichthys.VolumeResource
	(*VolumeList)(nil),     // 2: ichthys.VolumeList
	nil,                    // 3: ichthys.VolumeManifest.AnnotationsEntry
}
var file_volres_ichthys_v1_volres_service_proto_depIdxs = []int32{
	3, // 0: ichthys.VolumeManifest.annotations:type_name -> ichthys.VolumeManifest.AnnotationsEntry
	1, // 1: ichthys.VolumeManifest.root:type_name -> ichthys.VolumeResource
	1, // 2: ichthys.VolumeResource.children:type_name -> ichthys.VolumeResource
	0, // 3: ichthys.VolumeList.volumes:type_name -> ichthys.VolumeManifest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_volres_ichthys_v1_volres_service_proto_init() }
func file_volres_ichthys_v1_volres_service_proto_init() {
	if File_volres_ichthys_v1_volres_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volres_ichthys_v1_volres_service_proto_rawDesc), len(file_volres_ichthys_v1_volres_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_volres_ichthys_v1_volres_service_proto_goTypes,
		DependencyIndexes: file_volres_ichthys_v1_volres_service_proto_depIdxs,
		MessageInfos:      file_volres_ichthys_v1_volres_service_proto_msgTypes,
	}.Build()
	File_volres_ichthys_v1_volres_service_proto = out.File
	file_volres_ichthys_v1_volres_service_proto_goTypes = nil
	file_volres_ichthys_v1_volres_service_proto_depIdxs = nil
}
