// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nodesentinel/v1/nodesentinel.proto

package nodesentinelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueValidationWorkRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ArtifactKind        string                 `protobuf:"bytes,1,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	ImageRepository     string                 `protobuf:"bytes,2,opt,name=image_repository,json=imageRepository,proto3" json:"image_repository,omitempty"`
	ImageDigest         string                 `protobuf:"bytes,3,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	StableRef           string                 `protobuf:"bytes,4,opt,name=stable_ref,json=stableRef,proto3" json:"stable_ref,omitempty"`
	ToolName            string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Version             string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	CasHash             string                 `protobuf:"bytes,7,opt,name=cas_hash,json=casHash,proto3" json:"cas_hash,omitempty"`
	RequestedActions    []string               `protobuf:"bytes,8,rep,name=requested_actions,json=requestedActions,proto3" json:"requested_actions,omitempty"`
	RequestedFixtureSet string                 `protobuf:"bytes,9,opt,name=requested_fixture_set,json=requestedFixtureSet,proto3" json:"requested_fixture_set,omitempty"`
	// validation_request_id identifies one logical validation request (NOT a
	// build): NodeVault generates a fresh one per logical request (a build's
	// initial validation, a manual re-validation, a re-run after a fixture/
	// profile change, ...) and reuses the same value only when retrying the
	// exact same request after a transport/process failure. NodeSentinel
	// treats this as an idempotency key: repeating it with an identical
	// request returns the existing job; repeating it with a different
	// request is rejected (FAILED_PRECONDITION) rather than silently
	// returning the wrong job. Required — requests without it are rejected.
	ValidationRequestId string `protobuf:"bytes,10,opt,name=validation_request_id,json=validationRequestId,proto3" json:"validation_request_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnqueueValidationWorkRequest) Reset() {
	*x = EnqueueValidationWorkRequest{}
	mi := &file_nodesentinel_v1_nodesentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueValidationWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueValidationWorkRequest) ProtoMessage() {}

func (x *EnqueueValidationWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodesentinel_v1_nodesentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueValidationWorkRequest.ProtoReflect.Descriptor instead.
func (*EnqueueValidationWorkRequest) Descriptor() ([]byte, []int) {
	return file_nodesentinel_v1_nodesentinel_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueValidationWorkRequest) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetImageRepository() string {
	if x != nil {
		return x.ImageRepository
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetStableRef() string {
	if x != nil {
		return x.StableRef
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetCasHash() string {
	if x != nil {
		return x.CasHash
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetRequestedActions() []string {
	if x != nil {
		return x.RequestedActions
	}
	return nil
}

func (x *EnqueueValidationWorkRequest) GetRequestedFixtureSet() string {
	if x != nil {
		return x.RequestedFixtureSet
	}
	return ""
}

func (x *EnqueueValidationWorkRequest) GetValidationRequestId() string {
	if x != nil {
		return x.ValidationRequestId
	}
	return ""
}

type EnqueueValidationWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueValidationWorkResponse) Reset() {
	*x = EnqueueValidationWorkResponse{}
	mi := &file_nodesentinel_v1_nodesentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueValidationWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueValidationWorkResponse) ProtoMessage() {}

func (x *EnqueueValidationWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodesentinel_v1_nodesentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueValidationWorkResponse.ProtoReflect.Descriptor instead.
func (*EnqueueValidationWorkResponse) Descriptor() ([]byte, []int) {
	return file_nodesentinel_v1_nodesentinel_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueValidationWorkResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueValidationWorkResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_nodesentinel_v1_nodesentinel_proto protoreflect.FileDescriptor

const file_nodesentinel_v1_nodesentinel_proto_rawDesc = "" +
	"\n" +
	"\"nodesentinel/v1/nodesentinel.proto\x12\x0fnodesentinel.v1\"\x97\x03\n" +
	"\x1cEnqueueValidationWorkRequest\x12#\n" +
	"\rartifact_kind\x18\x01 \x01(\tR\fartifactKind\x12)\n" +
	"\x10image_repository\x18\x02 \x01(\tR\x0fimageRepository\x12!\n" +
	"\fimage_digest\x18\x03 \x01(\tR\vimageDigest\x12\x1d\n" +
	"\n" +
	"stable_ref\x18\x04 \x01(\tR\tstableRef\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x19\n" +
	"\bcas_hash\x18\a \x01(\tR\acasHash\x12+\n" +
	"\x11requested_actions\x18\b \x03(\tR\x10requestedActions\x122\n" +
	"\x15requested_fixture_set\x18\t \x01(\tR\x13requestedFixtureSet\x122\n" +
	"\x15validation_request_id\x18\n" +
	" \x01(\tR\x13validationRequestId\"N\n" +
	"\x1dEnqueueValidationWorkResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x88\x01\n" +
	"\x0eIngressService\x12v\n" +
	"\x15EnqueueValidationWork\x12-.nodesentinel.v1.EnqueueValidationWorkRequest\x1a..nodesentinel.v1.EnqueueValidationWorkResponseBEZCgithub.com/HeaInSeo/NodeVault/protos/nodesentinel/v1;nodesentinelv1b\x06proto3"

var (
	file_nodesentinel_v1_nodesentinel_proto_rawDescOnce sync.Once
	file_nodesentinel_v1_nodesentinel_proto_rawDescData []byte
)

func file_nodesentinel_v1_nodesentinel_proto_rawDescGZIP() []byte {
	file_nodesentinel_v1_nodesentinel_proto_rawDescOnce.Do(func() {
		file_nodesentinel_v1_nodesentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodesentinel_v1_nodesentinel_proto_rawDesc), len(file_nodesentinel_v1_nodesentinel_proto_rawDesc)))
	})
	return file_nodesentinel_v1_nodesentinel_proto_rawDescData
}

var file_nodesentinel_v1_nodesentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nodesentinel_v1_nodesentinel_proto_goTypes = []any{
	(*EnqueueValidationWorkRequest)(nil),  // 0: nodesentinel.v1.EnqueueValidationWorkRequest
	(*EnqueueValidationWorkResponse)(nil), // 1: nodesentinel.v1.EnqueueValidationWorkResponse
}
var file_nodesentinel_v1_nodesentinel_proto_depIdxs = []int32{
	0, // 0: nodesentinel.v1.IngressService.EnqueueValidationWork:input_type -> nodesentinel.v1.EnqueueValidationWorkRequest
	1, // 1: nodesentinel.v1.IngressService.EnqueueValidationWork:output_type -> nodesentinel.v1.EnqueueValidationWorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodesentinel_v1_nodesentinel_proto_init() }
func file_nodesentinel_v1_nodesentinel_proto_init() {
	if File_nodesentinel_v1_nodesentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodesentinel_v1_nodesentinel_proto_rawDesc), len(file_nodesentinel_v1_nodesentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodesentinel_v1_nodesentinel_proto_goTypes,
		DependencyIndexes: file_nodesentinel_v1_nodesentinel_proto_depIdxs,
		MessageInfos:      file_nodesentinel_v1_nodesentinel_proto_msgTypes,
	}.Build()
	File_nodesentinel_v1_nodesentinel_proto = out.File
	file_nodesentinel_v1_nodesentinel_proto_goTypes = nil
	file_nodesentinel_v1_nodesentinel_proto_depIdxs = nil
}
