// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tool/ichthys/v1/tool_service.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisplayName      string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Category         string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	InputFormats     []string               `protobuf:"bytes,5,rep,name=input_formats,json=inputFormats,proto3" json:"input_formats,omitempty"`
	OutputFormats    []string               `protobuf:"bytes,6,rep,name=output_formats,json=outputFormats,proto3" json:"output_formats,omitempty"`
	Resources        *Resources             `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	Signature        *Signature             `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	DocumentationUrl string                 `protobuf:"bytes,9,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	SecurityStatus   *SecurityStatus        `protobuf:"bytes,10,opt,name=security_status,json=securityStatus,proto3" json:"security_status,omitempty"`
	RegistryInfo     *RegistryInfo          `protobuf:"bytes,11,opt,name=registry_info,json=registryInfo,proto3" json:"registry_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolMetadata) Reset() {
	*x = ToolMetadata{}
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolMetadata) ProtoMessage() {}

func (x *ToolMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolMetadata.ProtoReflect.Descriptor instead.
func (*ToolMetadata) Descriptor() ([]byte, []int) {
	return file_tool_ichthys_v1_tool_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToolMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ToolMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ToolMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolMetadata) GetInputFormats() []string {
	if x != nil {
		return x.InputFormats
	}
	return nil
}

func (x *ToolMetadata) GetOutputFormats() []string {
	if x != nil {
		return x.OutputFormats
	}
	return nil
}

func (x *ToolMetadata) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ToolMetadata) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *ToolMetadata) GetSecurityStatus() *SecurityStatus {
	if x != nil {
		return x.SecurityStatus
	}
	return nil
}

func (x *ToolMetadata) GetRegistryInfo() *RegistryInfo {
	if x != nil {
		return x.RegistryInfo
	}
	return nil
}

type RegistryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryInfo) Reset() {
	*x = RegistryInfo{}
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryInfo) ProtoMessage() {}

func (x *RegistryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryInfo.ProtoReflect.Descriptor instead.
func (*RegistryInfo) Descriptor() ([]byte, []int) {
	return file_tool_ichthys_v1_tool_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegistryInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *RegistryInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RegistryInfo) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type Resources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MinCpuThreads  uint32                 `protobuf:"varint,1,opt,name=min_cpu_threads,json=minCpuThreads,proto3" json:"min_cpu_threads,omitempty"`
	RecCpuThreads  uint32                 `protobuf:"varint,2,opt,name=rec_cpu_threads,json=recCpuThreads,proto3" json:"rec_cpu_threads,omitempty"`
	MinMemoryMb    uint64                 `protobuf:"varint,3,opt,name=min_memory_mb,json=minMemoryMb,proto3" json:"min_memory_mb,omitempty"`
	RecMemoryMb    uint64                 `protobuf:"varint,4,opt,name=rec_memory_mb,json=recMemoryMb,proto3" json:"rec_memory_mb,omitempty"`
	TempDiskSizeMb uint64                 `protobuf:"varint,5,opt,name=temp_disk_size_mb,json=tempDiskSizeMb,proto3" json:"temp_disk_size_mb,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_tool_ichthys_v1_tool_service_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetMinCpuThreads() uint32 {
	if x != nil {
		return x.MinCpuThreads
	}
	return 0
}

func (x *Resources) GetRecCpuThreads() uint32 {
	if x != nil {
		return x.RecCpuThreads
	}
	return 0
}

func (x *Resources) GetMinMemoryMb() uint64 {
	if x != nil {
		return x.MinMemoryMb
	}
	return 0
}

func (x *Resources) GetRecMemoryMb() uint64 {
	if x != nil {
		return x.RecMemoryMb
	}
	return 0
}

func (x *Resources) GetTempDiskSizeMb() uint64 {
	if x != nil {
		return x.TempDiskSizeMb
	}
	return 0
}

type SecurityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Critical      int32                  `protobuf:"varint,1,opt,name=critical,proto3" json:"critical,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Medium        int32                  `protobuf:"varint,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Low           int32                  `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
	LastScanned   string                 `protobuf:"bytes,5,opt,name=last_scanned,json=lastScanned,proto3" json:"last_scanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityStatus) Reset() {
	*x = SecurityStatus{}
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatus) ProtoMessage() {}

func (x *SecurityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatus.ProtoReflect.Descriptor instead.
func (*SecurityStatus) Descriptor() ([]byte, []int) {
	return file_tool_ichthys_v1_tool_service_proto_rawDescGZIP(), []int{3}
}

func (x *SecurityStatus) GetCritical() int32 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *SecurityStatus) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *SecurityStatus) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *SecurityStatus) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *SecurityStatus) GetLastScanned() string {
	if x != nil {
		return x.LastScanned
	}
	return ""
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        bool                   `protobuf:"varint,1,opt,name=signed,proto3" json:"signed,omitempty"`
	Signers       []string               `protobuf:"bytes,2,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tool_ichthys_v1_tool_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tool_ichthys_v1_tool_service_proto_rawDescGZIP(), []int{4}
}

func (x *Signature) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *Signature) GetSigners() []string {
	if x != nil {
		return x.Signers
	}
	return nil
}

var File_tool_ichthys_v1_tool_service_proto protoreflect.FileDescriptor

const file_tool_ichthys_v1_tool_service_proto_rawDesc = "" +
	"\n" +
	"\"tool/ichthys/v1/tool_service.proto\x12\aichthys\"\xe4\x03\n" +
	"\fToolMetadata\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rinput_formats\x18\x05 \x03(\tR\finputFormats\x12%\n" +
	"\x0eoutput_formats\x18\x06 \x03(\tR\routputFormats\x120\n" +
	"\tresources\x18\a \x01(\v2\x12.ichthys.ResourcesR\tresources\x120\n" +
	"\tsignature\x18\b \x01(\v2\x12.ichthys.SignatureR\tsignature\x12+\n" +
	"\x11documentation_url\x18\t \x01(\tR\x10documentationUrl\x12@\n" +
	"\x0fsecurity_status\x18\n" +
	" \x01(\v2\x17.ichthys.SecurityStatusR\x0esecurityStatus\x12:\n" +
	"\rregistry_info\x18\v \x01(\v2\x15.ichthys.RegistryInfoR\fregistryInfo\"l\n" +
	"\fRegistryInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\"\xce\x01\n" +
	"\tResources\x12&\n" +
	"\x0fmin_cpu_threads\x18\x01 \x01(\rR\rminCpuThreads\x12&\n" +
	"\x0frec_cpu_threads\x18\x02 \x01(\rR\rrecCpuThreads\x12\"\n" +
	"\rmin_memory_mb\x18\x03 \x01(\x04R\vminMemoryMb\x12\"\n" +
	"\rrec_memory_mb\x18\x04 \x01(\x04R\vrecMemoryMb\x12)\n" +
	"\x11temp_disk_size_mb\x18\x05 \x01(\x04R\x0etempDiskSizeMb\"\x8d\x01\n" +
	"\x0eSecurityStatus\x12\x1a\n" +
	"\bcritical\x18\x01 \x01(\x05R\bcritical\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\x12\x16\n" +
	"\x06medium\x18\x03 \x01(\x05R\x06medium\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x05R\x03low\x12!\n" +
	"\flast_scanned\x18\x05 \x01(\tR\vlastScanned\"=\n" +
	"\tSignature\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\bR\x06signed\x12\x18\n" +
	"\asigners\x18\x02 \x03(\tR\asignersB=Z;github.com/HeaInSeo/NodeForge/protos/tool/ichthys/v1;toolv1b\x06proto3"

var (
	file_tool_ichthys_v1_tool_service_proto_rawDescOnce sync.Once
	file_tool_ichthys_v1_tool_service_proto_rawDescData []byte
)

func file_tool_ichthys_v1_tool_service_proto_rawDescGZIP() []byte {
	file_tool_ichthys_v1_tool_service_proto_rawDescOnce.Do(func() {
		file_tool_ichthys_v1_tool_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_ichthys_v1_tool_service_proto_rawDesc), len(file_tool_ichthys_v1_tool_service_proto_rawDesc)))
	})
	return file_tool_ichthys_v1_tool_service_proto_rawDescData
}

var file_tool_ichthys_v1_tool_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tool_ichthys_v1_tool_service_proto_goTypes = []any{
	(*ToolMetadata)(nil),   // 0: ichthys.ToolMetadata
	(*RegistryInfo)(nil),   // 1: ichthys.RegistryInfo
	(*Resources)(nil),      // 2: ichthys.Resources
	(*SecurityStatus)(nil), // 3: ichthys.SecurityStatus
	(*Signature)(nil),      // 4: ichthys.Signature
}
var file_tool_ichthys_v1_tool_service_proto_depIdxs = []int32{
	2, // 0: ichthys.ToolMetadata.resources:type_name -> ichthys.Resources
	4, // 1: ichthys.ToolMetadata.signature:type_name -> ichthys.Signature
	3, // 2: ichthys.ToolMetadata.security_status:type_name -> ichthys.SecurityStatus
	1, // 3: ichthys.ToolMetadata.registry_info:type_name -> ichthys.RegistryInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tool_ichthys_v1_tool_service_proto_init() }
func file_tool_ichthys_v1_tool_service_proto_init() {
	if File_tool_ichthys_v1_tool_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_ichthys_v1_tool_service_proto_rawDesc), len(file_tool_ichthys_v1_tool_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tool_ichthys_v1_tool_service_proto_goTypes,
		DependencyIndexes: file_tool_ichthys_v1_tool_service_proto_depIdxs,
		MessageInfos:      file_tool_ichthys_v1_tool_service_proto_msgTypes,
	}.Build()
	File_tool_ichthys_v1_tool_service_proto = out.File
	file_tool_ichthys_v1_tool_service_proto_goTypes = nil
	file_tool_ichthys_v1_tool_service_proto_depIdxs = nil
}
