package policy

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	nfv1 "github.com/HeaInSeo/NodeVault/protos/nodevault/v1"
)

func TestGetPolicyBundle_ReturnsBytes(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	payload := []byte("fake-wasm-bytes")
	if err := os.WriteFile(wasmPath, payload, 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	resp, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err != nil {
		t.Fatalf("GetPolicyBundle: %v", err)
	}
	if !bytes.Equal(resp.WasmBytes, payload) {
		t.Errorf("WasmBytes mismatch: got %q want %q", resp.WasmBytes, payload)
	}
	if resp.BuiltAt == 0 {
		t.Error("BuiltAt should be non-zero")
	}
}

func TestGetPolicyBundle_FileMissing(t *testing.T) {
	svc := &Service{wasmPath: "/nonexistent/dockguard.wasm"}
	_, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestListPolicies_ReturnsAllRules(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	if err := os.WriteFile(wasmPath, []byte("x"), 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}
	// policies.json is the sidecar generated by `make policies-json` in DockGuard.
	policiesJSON := `[
		{"rule_id":"DFM001","title":"Exactly one FROM required","description":"User Dockerfile must contain exactly one FROM instruction."},
		{"rule_id":"DFM002","title":"AS builder alias required","description":"FROM must include AS builder alias."},
		{"rule_id":"DFM003","title":"AS final stage reserved","description":"The alias 'final' is reserved; do not define it in user Dockerfiles."},
		{"rule_id":"DFM004","title":"COPY --from=builder prohibited","description":"COPY --from=builder must not appear in user-submitted Dockerfiles."},
		{"rule_id":"DGF001","title":"conda/mamba install version pinning required","description":"RUN conda/mamba/micromamba install must specify exact versions."},
		{"rule_id":"DGF002","title":"pip install version pinning required","description":"RUN pip install must specify exact versions."},
		{"rule_id":"DSF001","title":"Non-root USER required","description":"Dockerfile must specify a non-root USER instruction."},
		{"rule_id":"DSF002","title":"No secrets in ENV","description":"ENV must not contain secret variable names."},
		{"rule_id":"DSF003","title":"No remote ADD URLs","description":"ADD must not reference remote URLs."}
	]`
	if err := os.WriteFile(filepath.Join(dir, "policies.json"), []byte(policiesJSON), 0o600); err != nil {
		t.Fatalf("write policies.json: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	resp, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err != nil {
		t.Fatalf("ListPolicies: %v", err)
	}
	// DFM001-004 (multistage) + DSF001-003 (security) + DGF001-002 (genomics)
	wantRules := []string{
		"DFM001", "DFM002", "DFM003", "DFM004",
		"DSF001", "DSF002", "DSF003",
		"DGF001", "DGF002",
	}
	if len(resp.Policies) != len(wantRules) {
		t.Errorf("expected %d policies, got %d", len(wantRules), len(resp.Policies))
	}
	ids := map[string]bool{}
	for _, p := range resp.Policies {
		ids[p.RuleId] = true
	}
	for _, want := range wantRules {
		if !ids[want] {
			t.Errorf("missing policy rule %s", want)
		}
	}
}

func TestListPolicies_FileMissing(t *testing.T) {
	svc := &Service{wasmPath: "/nonexistent/dockguard.wasm"}
	_, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestListPolicies_PoliciesJSONMissing(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	if err := os.WriteFile(wasmPath, []byte("x"), 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}
	// policies.json intentionally not written

	svc := &Service{wasmPath: wasmPath}
	_, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err == nil {
		t.Fatal("expected error for missing policies.json, got nil")
	}
}

func TestNewService_DefaultPath(t *testing.T) {
	if err := os.Unsetenv("DOCKGUARD_WASM_PATH"); err != nil {
		t.Fatalf("Unsetenv: %v", err)
	}
	svc := NewService()
	if svc.wasmPath != defaultWasmPath {
		t.Errorf("default path: got %q want %q", svc.wasmPath, defaultWasmPath)
	}
}

func TestNewService_EnvOverride(t *testing.T) {
	t.Setenv("DOCKGUARD_WASM_PATH", "/custom/path.wasm")
	svc := NewService()
	if svc.wasmPath != "/custom/path.wasm" {
		t.Errorf("env override: got %q want %q", svc.wasmPath, "/custom/path.wasm")
	}
}
