// Package policy manages DockGuard policy bundles.
// PolicyService serves the pre-built dockguard.wasm bundle to NodeKit clients.
// The bundle path is configured via DOCKGUARD_WASM_PATH (default: assets/policy/dockguard.wasm).
// Policy metadata is read from policies.json in the same directory as dockguard.wasm.
// policies.json is generated by `make policies-json` in the DockGuard repository.
package policy

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	nfv1 "github.com/HeaInSeo/NodeVault/protos/nodevault/v1"
)

const defaultWasmPath = "assets/policy/dockguard.wasm"

// Service implements PolicyServiceServer.
type Service struct {
	nfv1.UnimplementedPolicyServiceServer
	wasmPath string
}

// NewService creates a PolicyService.
// DOCKGUARD_WASM_PATH env overrides the default bundle path.
func NewService() *Service {
	path := os.Getenv("DOCKGUARD_WASM_PATH")
	if path == "" {
		path = defaultWasmPath
	}
	return &Service{wasmPath: path}
}

// policyEntry mirrors the JSON structure produced by `make policies-json` in DockGuard.
type policyEntry struct {
	RuleID      string `json:"rule_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

// GetPolicyBundle reads the .wasm bundle from disk and returns it.
func (s *Service) GetPolicyBundle(_ context.Context, _ *nfv1.GetPolicyBundleRequest) (*nfv1.PolicyBundle, error) {
	data, err := os.ReadFile(s.wasmPath)
	if err != nil {
		return nil, fmt.Errorf("read wasm bundle %q: %w", s.wasmPath, err)
	}

	info, err := os.Stat(s.wasmPath)
	if err != nil {
		return nil, fmt.Errorf("stat wasm bundle: %w", err)
	}

	version := filepath.Base(filepath.Dir(s.wasmPath))
	if version == "." || version == "/" {
		version = "local"
	}

	return &nfv1.PolicyBundle{
		WasmBytes: data,
		Version:   version,
		BuiltAt:   info.ModTime().Unix(),
	}, nil
}

// ListPolicies reads policy metadata from policies.json (generated by `make policies-json`
// in the DockGuard repository) located alongside dockguard.wasm.
func (s *Service) ListPolicies(_ context.Context, _ *nfv1.ListPoliciesRequest) (*nfv1.ListPoliciesResponse, error) {
	info, err := os.Stat(s.wasmPath)
	if err != nil {
		return nil, fmt.Errorf("wasm bundle not found at %q: %w", s.wasmPath, err)
	}
	version := info.ModTime().Format(time.RFC3339)

	jsonPath := filepath.Join(filepath.Dir(s.wasmPath), "policies.json")
	//nolint:gosec // G304: jsonPath is derived from operator-configured wasmPath.
	raw, err := os.ReadFile(jsonPath)
	if err != nil {
		return nil, fmt.Errorf("read policies.json at %q: %w", jsonPath, err)
	}

	var entries []policyEntry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return nil, fmt.Errorf("parse policies.json: %w", err)
	}

	policies := make([]*nfv1.PolicyInfo, 0, len(entries))
	for _, e := range entries {
		policies = append(policies, &nfv1.PolicyInfo{
			RuleId:      e.RuleID,
			Name:        e.Title,
			Version:     version,
			Description: e.Description,
		})
	}

	return &nfv1.ListPoliciesResponse{
		BundleVersion: version,
		Policies:      policies,
	}, nil
}
