package policy

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	nfv1 "github.com/HeaInSeo/NodeVault/protos/nodevault/v1"
)

// validWasmPayload builds a minimal (fake) module that starts with the real wasm
// magic bytes, followed by arbitrary content, so tests can exercise the happy path
// without shipping a real compiled wasm binary as a fixture.
func validWasmPayload(body string) []byte {
	return append([]byte{0x00, 0x61, 0x73, 0x6d}, []byte(body)...)
}

func TestGetPolicyBundle_ReturnsBytes(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	payload := validWasmPayload("fake-wasm-bytes")
	if err := os.WriteFile(wasmPath, payload, 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	resp, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err != nil {
		t.Fatalf("GetPolicyBundle: %v", err)
	}
	if !bytes.Equal(resp.WasmBytes, payload) {
		t.Errorf("WasmBytes mismatch: got %q want %q", resp.WasmBytes, payload)
	}
	if resp.BuiltAt == 0 {
		t.Error("BuiltAt should be non-zero")
	}
}

func TestGetPolicyBundle_FileMissing(t *testing.T) {
	svc := &Service{wasmPath: "/nonexistent/dockguard.wasm"}
	_, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestGetPolicyBundle_VersionTracksModTime(t *testing.T) {
	dir := t.TempDir()

	oldPath := filepath.Join(dir, "old.wasm")
	if err := os.WriteFile(oldPath, validWasmPayload("old"), 0o600); err != nil {
		t.Fatalf("write old wasm: %v", err)
	}
	oldTime := time.Now().Add(-48 * time.Hour)
	if err := os.Chtimes(oldPath, oldTime, oldTime); err != nil {
		t.Fatalf("chtimes old: %v", err)
	}

	newPath := filepath.Join(dir, "new.wasm")
	if err := os.WriteFile(newPath, validWasmPayload("new"), 0o600); err != nil {
		t.Fatalf("write new wasm: %v", err)
	}
	newTime := time.Now()
	if err := os.Chtimes(newPath, newTime, newTime); err != nil {
		t.Fatalf("chtimes new: %v", err)
	}

	oldSvc := &Service{wasmPath: oldPath}
	oldResp, err := oldSvc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err != nil {
		t.Fatalf("GetPolicyBundle(old): %v", err)
	}

	newSvc := &Service{wasmPath: newPath}
	newResp, err := newSvc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err != nil {
		t.Fatalf("GetPolicyBundle(new): %v", err)
	}

	if oldResp.Version == newResp.Version {
		t.Fatalf("expected Version to differ between files with different mtimes, both got %q", oldResp.Version)
	}
	// Guard against the old bug where Version was hardcoded to the parent dir name
	// (e.g. "policy" for assets/policy/dockguard.wasm) regardless of the actual build.
	if oldResp.Version == "policy" || newResp.Version == "policy" {
		t.Fatalf("Version looks like the old directory-name constant, not an mtime: old=%q new=%q", oldResp.Version, newResp.Version)
	}
	if _, err := time.Parse(time.RFC3339, newResp.Version); err != nil {
		t.Errorf("Version %q is not RFC3339 (should match ListPolicies's BundleVersion format): %v", newResp.Version, err)
	}
}

func TestGetPolicyBundle_EmptyFileRejected(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	if err := os.WriteFile(wasmPath, []byte{}, 0o600); err != nil {
		t.Fatalf("write empty wasm: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	_, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err == nil {
		t.Fatal("expected error for empty wasm file, got nil (fake success)")
	}
}

func TestGetPolicyBundle_TruncatedFileRejected(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	// Missing the wasm magic header entirely — simulates a truncated/half-copied file.
	if err := os.WriteFile(wasmPath, []byte("not-a-wasm-module"), 0o600); err != nil {
		t.Fatalf("write bogus wasm: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	_, err := svc.GetPolicyBundle(context.Background(), &nfv1.GetPolicyBundleRequest{})
	if err == nil {
		t.Fatal("expected error for wasm file missing magic bytes, got nil (fake success)")
	}
}

func TestListPolicies_ReturnsAllRules(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	if err := os.WriteFile(wasmPath, []byte("x"), 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}
	// policies.json is the sidecar generated by `make policies-json` in DockGuard.
	policiesJSON := `[
		{"rule_id":"DFM001","title":"Exactly one FROM required","description":"User Dockerfile must contain exactly one FROM instruction."},
		{"rule_id":"DFM002","title":"AS builder alias required","description":"FROM must include AS builder alias."},
		{"rule_id":"DFM003","title":"AS final stage reserved","description":"The alias 'final' is reserved; do not define it in user Dockerfiles."},
		{"rule_id":"DFM004","title":"COPY --from=builder prohibited","description":"COPY --from=builder must not appear in user-submitted Dockerfiles."},
		{"rule_id":"DGF001","title":"conda/mamba install version pinning required","description":"RUN conda/mamba/micromamba install must specify exact versions."},
		{"rule_id":"DGF002","title":"pip install version pinning required","description":"RUN pip install must specify exact versions."},
		{"rule_id":"DSF001","title":"Non-root USER required","description":"Dockerfile must specify a non-root USER instruction."},
		{"rule_id":"DSF002","title":"No secrets in ENV","description":"ENV must not contain secret variable names."},
		{"rule_id":"DSF003","title":"No remote ADD URLs","description":"ADD must not reference remote URLs."}
	]`
	if err := os.WriteFile(filepath.Join(dir, "policies.json"), []byte(policiesJSON), 0o600); err != nil {
		t.Fatalf("write policies.json: %v", err)
	}

	svc := &Service{wasmPath: wasmPath}
	resp, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err != nil {
		t.Fatalf("ListPolicies: %v", err)
	}
	// DFM001-004 (multistage) + DSF001-003 (security) + DGF001-002 (genomics)
	wantRules := []string{
		"DFM001", "DFM002", "DFM003", "DFM004",
		"DSF001", "DSF002", "DSF003",
		"DGF001", "DGF002",
	}
	if len(resp.Policies) != len(wantRules) {
		t.Errorf("expected %d policies, got %d", len(wantRules), len(resp.Policies))
	}
	ids := map[string]bool{}
	for _, p := range resp.Policies {
		ids[p.RuleId] = true
	}
	for _, want := range wantRules {
		if !ids[want] {
			t.Errorf("missing policy rule %s", want)
		}
	}
}

func TestListPolicies_FileMissing(t *testing.T) {
	svc := &Service{wasmPath: "/nonexistent/dockguard.wasm"}
	_, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestListPolicies_PoliciesJSONMissing(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "dockguard.wasm")
	if err := os.WriteFile(wasmPath, []byte("x"), 0o600); err != nil {
		t.Fatalf("write wasm: %v", err)
	}
	// policies.json intentionally not written

	svc := &Service{wasmPath: wasmPath}
	_, err := svc.ListPolicies(context.Background(), &nfv1.ListPoliciesRequest{})
	if err == nil {
		t.Fatal("expected error for missing policies.json, got nil")
	}
}

func TestNewService_DefaultPath(t *testing.T) {
	if err := os.Unsetenv("DOCKGUARD_WASM_PATH"); err != nil {
		t.Fatalf("Unsetenv: %v", err)
	}
	svc := NewService()
	if svc.wasmPath != defaultWasmPath {
		t.Errorf("default path: got %q want %q", svc.wasmPath, defaultWasmPath)
	}
}

func TestNewService_EnvOverride(t *testing.T) {
	t.Setenv("DOCKGUARD_WASM_PATH", "/custom/path.wasm")
	svc := NewService()
	if svc.wasmPath != "/custom/path.wasm" {
		t.Errorf("env override: got %q want %q", svc.wasmPath, "/custom/path.wasm")
	}
}
